// Centralized app state (Phase 13 scaffold)

import {
  PALETTE_THEMES,
  countryPalette,
  defaultCountryPalette,
  legacyDefaultCountryPalette,
  defaultZoom,
  countryNames,
  countryPresets,
  createDefaultPhysicalStyleConfig,
  createDefaultLakeStyleConfig,
  createDefaultUrbanStyleConfig,
  createDefaultCityLayerStyleConfig,
  createDefaultTransportOverviewStyleConfig,
  createDefaultTextureStyleConfig,
  createDefaultDayNightStyleConfig,
  createDefaultAnnotationView,
  createDefaultTransportWorkbenchDisplayConfigs,
  normalizeExportWorkbenchUiState
} from "./state_defaults.js";

export * from "./state_defaults.js";

export const state = {
  bootPhase: "shell",
  bootMessage: "Starting workspace…",
  bootProgress: 0,
  bootBlocking: true,
  bootPreviewVisible: false,
  bootError: "",
  bootCanContinueWithoutScenario: false,
  startupInteractionMode: "readonly",
  startupReadonly: false,
  startupReadonlyReason: "",
  setStartupReadonlyStateFn: null,
  startupReadonlyUnlockInFlight: false,
  startupReadonlySince: 0,
  interactionInfrastructureReady: true,
  interactionInfrastructureBuildInFlight: false,
  interactionInfrastructureStage: "idle",
  bootMetrics: {},
  startupBootCacheState: {
    enabled: false,
    baseTopology: "idle",
    localization: "idle",
    scenarioBootstrap: "idle",
  },
  locales: { ui: {}, geo: {} },
  baseLocalizationLevel: "full",
  baseLocalizationDataState: "idle",
  baseLocalizationDataError: "",
  baseLocalizationDataPromise: null,
  baseGeoLocales: {},
  geoAliasToStableKey: {},
  baseGeoAliasToStableKey: {},
  currentLanguage: globalThis.currentLanguage || "en",
  topology: null,
  topologyPrimary: null,
  topologyDetail: null,
  runtimePoliticalTopology: null,
  defaultRuntimePoliticalTopology: null,
  ruCityOverrides: null,
  topologyBundleMode: "single",
  renderProfile: "auto",
  detailDeferred: false,
  detailSourceRequested: "na_v2",
  detailPromotionInFlight: false,
  detailPromotionCompleted: false,
  scenarioApplyInFlight: false,
  scenarioRegistry: null,
  scenarioBundleCacheById: {},
  activeScenarioChunks: {
    scenarioId: "",
    loadedChunkIds: [],
    payloadByChunkId: {},
    mergedLayerPayloads: {},
    lruChunkIds: [],
  },
  runtimeChunkLoadState: {
    shellStatus: "idle",
    registryStatus: "idle",
    refreshScheduled: false,
    refreshTimerId: null,
    pendingReason: "",
    pendingDelayMs: null,
    focusCountryOverride: "",
    zoomEndChunkVisibleMetric: null,
    lastZoomEndToChunkVisibleMetric: null,
    pendingPromotion: null,
    inFlightByChunkId: {},
    errorByChunkId: {},
    lastSelection: null,
  },
  activeScenarioId: "",
  scenarioBorderMode: "canonical",
  scenarioViewMode: "ownership",
  activeScenarioManifest: null,
  scenarioCountriesByTag: {},
  scenarioFixedOwnerColors: {},
  defaultReleasableCatalog: null,
  releasableCatalog: null,
  scenarioReleasableIndex: {
    byTag: {},
    childTagsByParent: {},
    consumedPresetNamesByParentLookup: {},
  },
  defaultReleasablePresetOverlays: {},
  scenarioReleasablePresetOverlays: {},
  releasableBoundaryVariantByTag: {},
  scenarioAudit: null,
  scenarioAuditUi: {
    loading: false,
    loadedForScenarioId: "",
    errorMessage: "",
  },
  scenarioBaselineHash: "",
  scenarioBaselineOwnersByFeatureId: {},
  scenarioControllersByFeatureId: {},
  scenarioAutoShellOwnerByFeatureId: {},
  scenarioAutoShellControllerByFeatureId: {},
  scenarioShellOverlayRevision: 0,
  scenarioBaselineControllersByFeatureId: {},
  scenarioBaselineCoresByFeatureId: {},
  scenarioControllerRevision: 0,
  scenarioReliefOverlayRevision: 0,
  scenarioOwnerControllerDiffCount: 0,
  scenarioDataHealth: {
    expectedFeatureCount: 0,
    runtimeFeatureCount: 0,
    ratio: 1,
    minRatio: 0.7,
    warning: "",
    severity: "",
  },
  parentBordersVisible: true,
  scenarioParentBorderEnabledBeforeActivate: null,
  scenarioPaintModeBeforeActivate: null,
  scenarioOceanFillBeforeActivate: null,
  scenarioDisplaySettingsBeforeActivate: null,
  activeScenarioPerformanceHints: null,
  landData: null,
  landDataFull: null,
  activeScenarioMeshPack: null,
  specialZonesData: null,
  specialZonesExternalData: null,
  contextLayerExternalDataByName: {},
  contextLayerRevision: 0,
  contextLayerLoadStateByName: {
    rivers: "idle",
    urban: "idle",
    airports: "idle",
    ports: "idle",
    roads: "idle",
    road_labels: "idle",
    railways: "idle",
    rail_stations_major: "idle",
    physical: "idle",
    physical_semantics: "idle",
    physical_contours_major: "idle",
    physical_contours_minor: "idle",
  },
  contextLayerLoadErrorByName: {},
  contextLayerLoadPromiseByName: {},
  specialZones: {},
  waterRegionsData: null,
  scenarioWaterRegionsData: null,
  scenarioWaterOverlayVersionTag: "",
  scenarioSpecialRegionsData: null,
  scenarioRuntimeTopologyData: null,
  scenarioRuntimeTopologyVersionTag: "",
  scenarioPoliticalChunkData: null,
  scenarioLandMaskData: null,
  scenarioContextLandMaskData: null,
  scenarioLandMaskVersionTag: "",
  scenarioContextLandMaskVersionTag: "",
  scenarioReliefOverlaysData: null,
  scenarioBathymetryTopologyData: null,
  scenarioBathymetryBandsData: null,
  scenarioBathymetryContoursData: null,
  scenarioBathymetryTopologyUrl: "",
  scenarioDistrictGroupsData: null,
  scenarioDistrictGroupByFeatureId: new Map(),
  scenarioDistrictSharedTemplatesData: null,
  scenarioGeoLocalePatchData: null,
  scenarioCityOverridesData: null,
  scenarioHydrationHealthGate: {
    status: "idle",
    reason: "",
    checkedAt: 0,
    attemptedRetry: false,
    ownerFeatureOverlapRatio: 1,
    ownerFeatureOverlapCount: 0,
    ownerFeatureRenderedCount: 0,
    degradedWaterOverlay: false,
  },
  riversData: null,
  airportsData: null,
  portsData: null,
  roadsData: null,
  roadLabelsData: null,
  railwaysData: null,
  railStationsMajorData: null,
  oceanData: null,
  globalBathymetryTopologyData: null,
  globalBathymetryBandsData: null,
  globalBathymetryContoursData: null,
  globalBathymetryTopologyUrl: "",
  activeBathymetryBandsData: null,
  activeBathymetryContoursData: null,
  activeBathymetrySource: "none",
  activeBathymetryTopologyUrl: "",
  oceanMaskMode: "topology_ocean",
  oceanMaskQuality: 1,
  landBgData: null,
  urbanData: null,
  urbanLayerCapability: null,
  worldCitiesData: null,
  baseCityAliasesData: null,
  baseCityDataState: "idle",
  baseCityDataError: "",
  baseCityDataPromise: null,
  physicalData: null,
  physicalSemanticsData: null,
  physicalContourMajorData: null,
  physicalContourMinorData: null,
  hierarchyData: null,
  hierarchyGroupsByCode: new Map(),
  countryGroupsData: null,
  countryGroupMetaByCode: new Map(),
  countryInteractionPoliciesByCode: new Map(),
  layerDataDiagnostics: {},
  contextLayerSourceByName: {},

  width: 0,
  height: 0,
  dpr: globalThis.devicePixelRatio || 1,
  dprStage: "idle",
  dprInteractiveScale: 0.72,
  dprLastStageSwitchAt: 0,

  // Resolved colors used by canvas render/legend.
  colors: {},
  // Country-level base colors (applies when no subdivision override exists).
  countryBaseColors: {},
  sovereignBaseColors: {},
  // Subdivision-level explicit color overrides keyed by feature ID.
  featureOverrides: {},
  visualOverrides: {},
  waterRegionOverrides: {},
  specialRegionOverrides: {},
  sovereigntyByFeatureId: {},
  sovereigntyInitialized: false,
  sovereigntyRevision: 0,
  mapSemanticMode: "political",
  dynamicBordersEnabled: true,
  dynamicBordersDirty: false,
  dynamicBordersDirtyReason: "",
  pendingDynamicBorderTimerId: null,
  ownerToFeatureIds: new Map(),
  runtimeFeatureIndexById: new Map(),
  runtimeFeatureIds: [],
  runtimeNeighborGraph: [],
  runtimeCanonicalCountryByFeatureId: {},
  runtimePoliticalMetaSeed: null,
  runtimePoliticalMetaReadyFromWorker: false,
  getViewportGeoBoundsFn: null,
  scheduleScenarioChunkRefreshFn: null,
  paintMode: "visual",
  activeSovereignCode: "",
  sovereignContrastWarnings: [],
  // Click/paint granularity: subdivision | country.
  interactionGranularity: "subdivision",
  // Double-click quick-fill scope: parent | country.
  batchFillScope: "parent",
  paletteRegistry: null,
  activePaletteId: "hoi4_vanilla",
  activePaletteMeta: null,
  activePalettePack: null,
  activePaletteMap: null,
  activePaletteOceanMeta: null,
  palettePackCacheById: {},
  paletteMapCacheById: {},
  paletteLoadErrorById: {},
  fixedPaletteColorsByIso2: {},
  resolvedDefaultCountryPalette: { ...defaultCountryPalette },
  paletteLibraryOpen: false,
  paletteLibrarySearch: "",
  paletteLibraryEntries: [],
  paletteQuickSwatches: [],
  currentPaletteTheme: "HOI4 Vanilla",
  colorMode: "political",
  selectedColor: PALETTE_THEMES["HOI4 Vanilla"][0],
  selectedInspectorCountryCode: "",
  inspectorExpansionInitialized: false,
  inspectorHighlightCountryCode: "",
  currentTool: "fill",
  brushModeEnabled: false,
  brushPanModifierActive: false,
  activeDockPopover: "",
  isDirty: false,
  dirtyRevision: 0,
  onboardingDismissed: false,
  hoveredId: null,
  hoveredWaterRegionId: null,
  hoveredSpecialRegionId: null,
  devHoverHit: null,
  devSelectedHit: null,
  devSelectionFeatureIds: new Set(),
  devSelectionOrder: [],
  devSelectionModeEnabled: false,
  devSelectionLimit: 200,
  devSelectionOverlayDirty: true,
  devSelectionSortMode: "selection",
  devClipboardPreviewFormat: "names_with_ids",
  devClipboardFallbackText: "",
  devRuntimeMeta: null,
  devRuntimeMetaError: "",
  devScenarioEditor: {
    targetOwnerCode: "",
    isSaving: false,
    lastSavedAt: "",
    lastSavedPath: "",
    lastSaveMessage: "",
    lastSaveTone: "",
  },
  devScenarioTagCreator: {
    tag: "",
    nameEn: "",
    nameZh: "",
    colorHex: "#5D7CBA",
    parentOwnerTag: "",
    selectedInspectorGroupId: "",
    inspectorGroupId: "",
    inspectorGroupLabel: "",
    inspectorGroupAnchorId: "",
    duplicateTag: false,
    tagLengthHint: "",
    isColorPopoverOpen: false,
    recentColors: [],
    recentColorsLoaded: false,
    isSaving: false,
    lastSavedAt: "",
    lastSavedPath: "",
    lastSaveMessage: "",
    lastSaveTone: "",
  },
  devScenarioCountryEditor: {
    tag: "",
    nameEn: "",
    nameZh: "",
    isSaving: false,
    lastSavedAt: "",
    lastSavedPath: "",
    lastSaveMessage: "",
    lastSaveTone: "",
  },
  devScenarioTagInspector: {
    threshold: 3,
    selectedTag: "",
  },
  devScenarioCapitalEditor: {
    tag: "",
    searchQuery: "",
    isSaving: false,
    lastSavedAt: "",
    lastSavedPath: "",
    lastSaveMessage: "",
    lastSaveTone: "",
  },
  devLocaleEditor: {
    featureId: "",
    en: "",
    zh: "",
    isSaving: false,
    lastSavedAt: "",
    lastSavedPath: "",
  },
  devScenarioDistrictEditor: {
    tag: "",
    tagMode: "auto",
    manualTag: "",
    inferredTag: "",
    templateTag: "",
    selectedDistrictId: "",
    nameEn: "",
    nameZh: "",
    loadedScenarioId: "",
    loadedTag: "",
    draftTag: null,
    isSaving: false,
    isTemplateSaving: false,
    isTemplateApplying: false,
    lastSavedAt: "",
    lastSavedPath: "",
    lastSaveMessage: "",
    lastSaveTone: "",
  },
  hoverOverlayDirty: true,
  inspectorOverlayDirty: true,
  specialZonesOverlayDirty: true,
  frontlineOverlayDirty: true,
  operationalLinesDirty: true,
  operationGraphicsDirty: true,
  unitCountersDirty: true,
  tooltipRafHandle: null,
  tooltipPendingState: null,
  selectedWaterRegionId: "",
  selectedSpecialRegionId: "",
  zoomTransform: defaultZoom,
  showWaterRegions: true,
  showOpenOceanRegions: false,
  allowOpenOceanSelect: false,
  allowOpenOceanPaint: false,
  showScenarioSpecialRegions: true,
  showScenarioReliefOverlays: true,
  showCityPoints: true,
  showUrban: true,
  showPhysical: true,
  showRivers: true,
  showTransport: true,
  showAirports: false,
  showPorts: false,
  showRail: false,
  showRoad: false,
  showSpecialZones: false,
  cityLayerRevision: 0,
  manualSpecialZones: {
    type: "FeatureCollection",
    features: [],
  },
  annotationView: createDefaultAnnotationView(),
  operationalLines: [],
  operationGraphics: [],
  unitCounters: [],
  specialZoneEditor: {
    active: false,
    vertices: [],
    zoneType: "custom",
    label: "",
    selectedId: null,
    counter: 1,
  },
  operationGraphicsEditor: {
    active: false,
    mode: "idle",
    collection: "operationGraphics",
    points: [],
    kind: "attack",
    label: "",
    stylePreset: "attack",
    stroke: "",
    width: 0,
    opacity: 1,
    selectedId: null,
    selectedVertexIndex: -1,
    counter: 1,
  },
  unitCounterEditor: {
    active: false,
    renderer: "game",
    label: "",
    sidc: "",
    symbolCode: "",
    nationTag: "",
    nationSource: "display",
    presetId: "",
    unitType: "",
    echelon: "",
    subLabel: "",
    strengthText: "",
    baseFillColor: "",
    organizationPct: 78,
    equipmentPct: 74,
    statsPresetId: "regular",
    statsSource: "preset",
    size: "medium",
    selectedId: null,
    counter: 1,
  },
  operationalLineEditor: {
    active: false,
    mode: "idle",
    points: [],
    kind: "frontline",
    label: "",
    stylePreset: "frontline",
    stroke: "",
    width: 0,
    opacity: 1,
    selectedId: null,
    selectedVertexIndex: -1,
    counter: 1,
  },
  strategicOverlayUi: {
    activeMode: "idle",
    modalOpen: false,
    modalSection: "line",
    modalEntityId: "",
    modalEntityType: "",
    counterEditorModalOpen: false,
    counterCatalogSource: "internal",
    counterCatalogCategory: "all",
    counterCatalogQuery: "",
    hoi4CounterCategory: "all",
    hoi4CounterQuery: "",
    hoi4CounterVariant: "small",
  },
  transportWorkbenchUi: {
    open: false,
    activeFamily: "road",
    activeInspectorTab: "inspect",
    sampleCountry: "Japan",
    previewMode: "bounded_zoom_pan",
    previewAssetId: "japan_carrier_v3",
    previewInteractionMode: "bounded_zoom_pan",
    previewCamera: {
      scale: 1,
      translateX: 0,
      translateY: 0,
    },
    compareHeld: false,
    layerOrder: [
      "road",
      "rail",
      "airport",
      "port",
      "mineral_resources",
      "energy_facilities",
      "industrial_zones",
      "logistics_hubs",
    ],
    familyConfigs: {
      road: {},
      rail: {},
      airport: {},
      port: {},
      mineral_resources: {},
      energy_facilities: {},
      industrial_zones: {},
      logistics_hubs: {},
    },
    displayConfigs: createDefaultTransportWorkbenchDisplayConfigs(),
    sectionOpen: {
      road: {},
      rail: {},
      airport: {},
      port: {},
      mineral_resources: {},
      energy_facilities: {},
      industrial_zones: {},
      logistics_hubs: {},
    },
    shellPhase: "road-live-preview",
    restoreLeftDrawer: false,
    restoreRightDrawer: false,
  },
  exportWorkbenchUi: normalizeExportWorkbenchUiState(null),
  cachedBorders: null,
  cachedCountryBorders: null,
  cachedDynamicOwnerBorders: null,
  cachedScenarioOpeningOwnerBorders: null,
  cachedFrontlineMesh: null,
  cachedFrontlineMeshHash: "",
  cachedFrontlineLabelAnchors: [],
  cachedFrontlineLabelAnchorsHash: "",
  cachedProvinceBorders: null,
  cachedProvinceBordersByCountry: new Map(),
  cachedLocalBorders: null,
  cachedLocalBordersByCountry: new Map(),
  cachedDetailAdmBorders: null,
  cachedDynamicBordersHash: null,
  cachedCoastlines: null,
  cachedCoastlinesHigh: null,
  cachedCoastlinesMid: null,
  cachedCoastlinesLow: null,
  cachedParentBordersByCountry: new Map(),
  cachedGridLines: null,
  parentBorderSupportedCountries: [],
  parentBorderEnabledByCountry: {},
  parentBorderMetaByCountry: {},
  parentGroupByFeatureId: new Map(),
  referenceImageUrl: null,
  referenceImageState: {
    opacity: 0.6,
    scale: 1,
    offsetX: 0,
    offsetY: 0,
  },
  styleConfig: {
    internalBorders: {
      color: "#cccccc",
      colorMode: "auto",
      opacity: 1,
      width: 0.5,
    },
    empireBorders: {
      color: "#666666",
      width: 1.0,
    },
    coastlines: {
      color: "#333333",
      width: 1.2,
    },
    parentBorders: {
      color: "#4b5563",
      opacity: 0.85,
      width: 1.1,
    },
    ocean: {
      preset: "flat",
      fillColor: "#aadaff",
      opacity: 0.72,
      scale: 1,
      contourStrength: 0.75,
      experimentalAdvancedStyles: false,
      coastalAccentEnabled: true,
      shallowBandFadeEndZoom: 2.8,
      midBandFadeEndZoom: 3.4,
      deepBandFadeEndZoom: 4.2,
      scenarioSyntheticContourFadeEndZoom: 3.0,
      scenarioShallowContourFadeEndZoom: 3.4,
    },
    lakes: createDefaultLakeStyleConfig(),
    cityPoints: {
      ...createDefaultCityLayerStyleConfig(),
    },
    urban: createDefaultUrbanStyleConfig(),
    physical: {
      ...createDefaultPhysicalStyleConfig(),
    },
    transportOverview: createDefaultTransportOverviewStyleConfig(),
    rivers: {
      color: "#3b82f6",
      opacity: 0.88,
      width: 0.5,
      outlineColor: "#e2efff",
      outlineWidth: 0.25,
      dashStyle: "solid",
    },
    specialZones: {
      disputedFill: "#f97316",
      disputedStroke: "#ea580c",
      wastelandFill: "#dc2626",
      wastelandStroke: "#b91c1c",
      customFill: "#8b5cf6",
      customStroke: "#6d28d9",
      opacity: 0.32,
      strokeWidth: 1.3,
      dashStyle: "dashed",
    },
    texture: createDefaultTextureStyleConfig(),
    dayNight: createDefaultDayNightStyleConfig(),
  },
  recentColors: [],
  historyPast: [],
  historyFuture: [],
  historyMax: 80,
  updateRecentUI: null,
  updateHistoryUIFn: null,
  updateLegendUI: null,
  updateSwatchUIFn: null,
  updatePaletteSourceUIFn: null,
  updatePaletteLibraryUIFn: null,
  updateScenarioUIFn: null,
  renderPaletteFn: null,
  updateToolUIFn: null,
  updateToolbarInputsFn: null,
  updatePaintModeUIFn: null,
  updateActiveSovereignUIFn: null,
  updateDynamicBorderStatusUIFn: null,
  updateZoomUIFn: null,
  updateTextureUIFn: null,
  updateWaterInteractionUIFn: null,
  updateTransportAppearanceUIFn: null,
  updateFacilityInfoCardUiFn: null,
  syncFacilityInfoCardVisibilityFn: null,
  updateScenarioSpecialRegionUIFn: null,
  updateScenarioReliefOverlayUIFn: null,
  updateParentBorderCountryListFn: null,
  updateSpecialZoneEditorUIFn: null,
  updateStrategicOverlayUIFn: null,
  updateScenarioContextBarFn: null,
  triggerScenarioGuideFn: null,
  toggleLeftPanelFn: null,
  toggleRightPanelFn: null,
  openTransportWorkbenchFn: null,
  closeTransportWorkbenchFn: null,
  refreshTransportWorkbenchUiFn: null,
  toggleDockFn: null,
  toggleDeveloperModeFn: null,
  persistViewSettingsFn: null,
  ensureBaseCityDataFn: null,
  ensureContextLayerDataFn: null,
  renderCountryListFn: null,
  refreshCountryListRowsFn: null,
  refreshCountryInspectorDetailFn: null,
  renderWaterRegionListFn: null,
  renderSpecialRegionListFn: null,
  renderPresetTreeFn: null,
  renderScenarioAuditPanelFn: null,
  updateDevWorkspaceUIFn: null,
  refreshColorStateFn: null,
  recomputeDynamicBordersNowFn: null,
  ensureDetailTopologyFn: null,
  renderNowFn: null,
  showToastFn: null,
  isEditingPreset: false,
  editingPresetRef: null,
  editingPresetIds: new Set(),
  customPresets: {},
  presetsState: {},
  legacyColorStateDirty: true,
  expandedInspectorContinents: new Set(),
  expandedInspectorReleaseParents: new Set(),
  expandedPresetCountries: new Set(),
  ui: {
    dockCollapsed: false,
    scenarioBarCollapsed: false,
    scenarioGuideDismissed: false,
    tutorialEntryVisible: true,
    tutorialDismissed: false,
    politicalEditingExpanded: false,
    scenarioVisualAdjustmentsOpen: false,
    developerMode: false,
    devWorkspaceExpanded: false,
    devWorkspaceCategory: "selection",
    rightSidebarTab: "inspector",
  },

  countryPalette,
  defaultCountryPalette,
  legacyDefaultCountryPalette,
  countryNames,
  countryPresets,

  landIndex: new Map(),
  countryToFeatureIds: new Map(),
  idToKey: new Map(),
  keyToId: new Map(),
  spatialIndex: null,
  spatialItems: [],
  spatialGrid: new Map(),
  spatialGridMeta: null,
  spatialItemsById: new Map(),
  waterRegionsById: new Map(),
  specialRegionsById: new Map(),
  waterSpatialIndex: null,
  waterSpatialItems: [],
  waterSpatialGrid: new Map(),
  waterSpatialGridMeta: null,
  waterSpatialItemsById: new Map(),
  specialSpatialIndex: null,
  specialSpatialItems: [],
  specialSpatialGrid: new Map(),
  specialSpatialGridMeta: null,
  specialSpatialItemsById: new Map(),

  TINY_AREA: 6,
  MOUSE_THROTTLE_MS: 16,
  lastMouseMoveTime: 0,
  hitCanvasDirty: true,
  hitCanvasTopologyRevision: 0,
  deferHitCanvasBuild: false,
  hitCanvasBuildScheduled: null,
  stagedMapDataToken: 0,
  stagedContextBaseHandle: null,
  stagedHitCanvasHandle: null,
  deferContextBasePass: false,
  deferContextBaseEnhancements: false,
  deferExactAfterSettle: false,
  exactAfterSettleHandle: null,
  zoomRenderScheduled: false,
  pendingZoomTransform: null,
  zoomGestureStartTransform: null,
  zoomGestureScaleDelta: 0,
  zoomGestureEndedAt: 0,
  adaptiveSettleProfile: null,
  pendingExactPoliticalFastFrame: false,
  debugCountryCoverage: null,
  isInteracting: false,
  renderPhase: "idle",
  phaseEnteredAt: 0,
  renderPhaseTimerId: null,
  pendingDayNightRefresh: false,
  colorRevision: 0,
  topologyRevision: 0,
  renderPassCache: {
    referenceTransform: null,
    referenceTransforms: {},
    canvases: {},
    layouts: {},
    signatures: {},
    borderSnapshot: {
      canvas: null,
      layout: null,
      referenceTransform: null,
      valid: false,
      reason: "init",
    },
    partialPoliticalDirtyIds: new Set(),
    politicalPathCache: new Map(),
    politicalPathCacheSignature: "",
    politicalPathCacheTransform: null,
    politicalPathWarmupQueue: [],
    politicalPathWarmupHandle: null,
    politicalPathWarmupSignature: "",
    dirty: {
      background: true,
      political: true,
      effects: true,
      contextBase: true,
      contextScenario: true,
      dayNight: true,
      borders: true,
    },
    reasons: {
      background: "init",
      political: "init",
      effects: "init",
      contextBase: "init",
      contextScenario: "init",
      dayNight: "init",
      borders: "init",
    },
    counters: {
      frames: 0,
      composites: 0,
      transformedFrames: 0,
      drawCanvas: 0,
      backgroundPassRenders: 0,
      politicalPassRenders: 0,
      effectsPassRenders: 0,
      contextPassRenders: 0,
      contextBasePassRenders: 0,
      contextScenarioPassRenders: 0,
      dayNightPassRenders: 0,
      borderPassRenders: 0,
      borderSnapshotRenders: 0,
      borderSnapshotReuses: 0,
      labelPassRenders: 0,
      hitCanvasRenders: 0,
      dynamicBorderRebuilds: 0,
      politicalPartialRepaints: 0,
      politicalPartialFallbacks: 0,
      politicalPartialCandidateCount: 0,
      politicalPartialPathCacheMisses: 0,
      politicalPartialPathBuild: 0,
      politicalPathCacheBuild: 0,
      politicalPathWarmupBuild: 0,
      politicalPathWarmupSlices: 0,
      politicalPathWarmupCancels: 0,
    },
    lastFrame: null,
    lastAction: "",
    lastActionDurationMs: 0,
    lastActionAt: 0,
    perfOverlayEnabled: false,
    overlayElement: null,
  },
  sidebarPerf: {
    counters: {
      fullListRenders: 0,
      rowRefreshes: 0,
      inspectorRenders: 0,
      presetTreeRenders: 0,
      legendRenders: 0,
    },
  },
  projectedBoundsById: new Map(),
  sphericalFeatureDiagnosticsById: new Map(),
};
