export const text = {
  zh:{edition:'原生地图工坊',open:'打开',save:'保存项目',export:'导出 PNG ↗',mapCaption:'每一片陆地与海洋，皆可创作。',select:'选择',paint:'绘制',pan:'平移',undo:'撤销',redo:'重做',fit:'全图',cancel:'取消',retry:'重新加载',findPlace:'寻找一片地方',colorHeading:'绘制颜色',hexColor:'十六进制颜色',applyColor:'为所选州上色',selectionHeading:'当前选择',clear:'清除',selectionEmpty:'点击地图，选择一个州。',multiHint:'Shift + 点击可多选 · 海域同样可编辑',stateId:'州 ID',referenceEntity:'参考实体',selectedCount:'已选州数',mapLabel:'地图标签',apply:'应用',labelHint:'留空恢复原名。参考实体保持只读。',mapLayers:'地图显示',borders:'州边界',labels:'地名标签',cities:'原生城市',shortcuts:'快捷键与操作',shortcutText:'V 选择 · B 绘制 · H 平移 · 0 全图。拖动平移，滚轮缩放；Ctrl/⌘ + Z 撤销，Shift + Z 重做；Ctrl/⌘ + S 保存。',footerNote:'独立项目 · 自由编辑',searchPlaceholder:'州名、实体或 ID',loading:'正在展开地图',loadDetail:'加载原生省份与州数据…',loadFailed:'地图未能打开',loadCancelled:'加载已取消',cancelledDetail:'数据加载已停止，可随时重新开始。',loadingPhase:'正在读取',unsaved:'有未保存修改',saved:'已保存',clean:'未修改',ready:'就绪',noResults:'未找到匹配的州',multiple:'个州',saveDone:'项目文件已生成。',openDone:'项目已打开。',exporting:'正在导出完整地图…',exportDone:'PNG 已生成。',discard:'当前项目有未保存修改。确定离开或打开其他项目？',badFile:'请选择不超过 10 MB 的 JSON 项目文件。',badColor:'请输入六位颜色，例如 #d17b55。',zoomIn:'放大',zoomOut:'缩小',mapAria:'地图：拖动平移，滚轮缩放，点击选择州',back:'返回 Scenario Forge',states:'州',provinces:'省份',lost:'图形上下文中断，等待恢复…',restored:'图形上下文已恢复',copied:'已应用',cityWarning:'城市数据未能加载；地图编辑仍可用。'},
  en:{edition:'NATIVE ATLAS WORKSHOP',open:'Open',save:'Save project',export:'Export PNG ↗',mapCaption:'A canvas of land and sea.',select:'Select',paint:'Paint',pan:'Pan',undo:'Undo',redo:'Redo',fit:'Fit',cancel:'Cancel',retry:'Reload map',findPlace:'FIND A PLACE',colorHeading:'Paint color',hexColor:'Hex color',applyColor:'Paint selected states',selectionHeading:'Selection',clear:'Clear',selectionEmpty:'Select a state on the map.',multiHint:'Shift + click to add · Water is editable too',stateId:'State ID',referenceEntity:'Reference entity',selectedCount:'Selected states',mapLabel:'Map label',apply:'Apply',labelHint:'Leave blank to restore the name. Reference entities are read-only.',mapLayers:'Map layers',borders:'State borders',labels:'Place labels',cities:'Native cities',shortcuts:'Shortcuts & controls',shortcutText:'V Select · B Paint · H Pan · 0 Fit. Drag to pan, scroll to zoom. Ctrl/⌘ + Z to undo, Shift + Z to redo, Ctrl/⌘ + S to save.',footerNote:'Independent project · Open canvas',searchPlaceholder:'State, entity or ID',loading:'Unfolding the atlas',loadDetail:'Loading native provinces and states…',loadFailed:'The map could not open',loadCancelled:'Loading cancelled',cancelledDetail:'Data loading stopped. You can restart at any time.',loadingPhase:'Reading',unsaved:'Unsaved changes',saved:'Saved',clean:'No changes',ready:'Ready',noResults:'No matching states',multiple:'states',saveDone:'Project file generated.',openDone:'Project opened.',exporting:'Exporting the complete map…',exportDone:'PNG generated.',discard:'This project has unsaved changes. Leave or open another project?',badFile:'Choose a JSON project file no larger than 10 MB.',badColor:'Enter a six-digit color, such as #d17b55.',zoomIn:'Zoom in',zoomOut:'Zoom out',mapAria:'Map: drag to pan, scroll to zoom, click to select a state',back:'Back to Scenario Forge',states:'states',provinces:'provinces',lost:'Graphics context lost; waiting for recovery…',restored:'Graphics context restored',copied:'Applied',cityWarning:'City data could not load; map editing is still available.'}
};

export function keyboardAction(event) {
  const key=event.key.toLowerCase();
  if(event.ctrlKey||event.metaKey){if(key==='s')return 'save';if(key==='o')return 'open';if(key==='z')return event.shiftKey?'redo':'undo';if(key==='y')return 'redo';return null;}
  if(event.altKey)return null;
  return {v:'select',b:'paint',h:'pan','0':'fit','+':'zoomIn','=':'zoomIn','-':'zoomOut',escape:'clear'}[key]||null;
}
export function validateProjectFile(file) {
  return !!file && typeof file.name==='string' && /\.json$/i.test(file.name) && Number.isFinite(file.size) && file.size>0 && file.size<=10*1024*1024;
}
export function parseHexColor(value) {
  const color=value.trim();
  return /^#[0-9a-f]{6}$/i.test(color)?color:null;
}
