import test from 'node:test';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import {webcrypto} from 'node:crypto';
import {createDocument} from '../src/document/document.js';
import {hitTest} from '../src/interaction/hit.js';
import {loadDataset,validateCore} from '../src/data/dataset.js';
import {createHgoSession} from '../src/session.js';
globalThis.crypto ||= webcrypto;
function fixture(){const core={schemaVersion:1,provinceIds:[null,0,17,98],provinceStateIds:[null,4,4,8],states:[{id:4,name:'Land',entityTag:'AAA',anchor:[.5,.5]},{id:8,name:'Sea',entityTag:'WTR',anchor:[1.5,1.5]}],entities:[{tag:'AAA',color:'#abcdef'},{tag:'WTR',color:'#123456',kind:'water'}]};return {manifest:{id:'test',revision:'r1',coordinateSpace:{width:2,height:2}},core,ids:new Uint16Array([1,2,0,3]),...validateCore(core,2,2)};}
test('exact hit preserves source province zero, tiny sea, nodata and edges',()=>{const d=fixture();assert.deepEqual(hitTest(d,.1,.1),{code:1,provinceId:0,stateId:'4'});assert.equal(hitTest(d,1.999,1.999).stateId,'8');assert.equal(hitTest(d,0,1),null);assert.equal(hitTest(d,2,0),null);assert.equal(hitTest(d,-.01,0),null);});
test('sea paint, label history, saved state and redo are independent of immutable reference',()=>{const d=fixture(),doc=createDocument(d);doc.paintStates(['8'],'#FF0000');assert.equal(doc.color('8'),'#ff0000');assert.equal(d.entityByTag.get('WTR').color,'#123456');doc.markSaved();assert.equal(doc.dirty,false);doc.label(8,'Ocean parcel');doc.undo();assert.equal(doc.dirty,false);doc.undo();assert.equal(doc.color('8'),'#123456');doc.redo();assert.equal(doc.color('8'),'#ff0000');assert.equal(doc.dirty,false);});
test('project validation is atomic for unknown IDs, wrong dataset and malformed view/layers',()=>{const d=fixture(),doc=createDocument(d);doc.paintStates([4],'#112233');const p=doc.serialize({x:1,y:1,scale:2},{borders:true,labels:true,cities:false}),before=JSON.stringify(p);for(const mutate of [p=>p.paint[999]='#445566',p=>p.dataset.revision='bad',p=>p.view.scale=Infinity,p=>p.layers.labels='yes',p=>p.labels[8]='x'.repeat(201)]){const bad=structuredClone(p);mutate(bad);assert.throws(()=>doc.load(bad));assert.equal(JSON.stringify(doc.serialize(p.view,p.layers)),before);assert.equal(doc.canUndo,true);}const restored=createDocument(d);restored.load(JSON.stringify(p));assert.equal(restored.color('4'),'#112233');assert.equal(restored.dirty,false);assert.equal(restored.canUndo,false);});
async function transport(d=fixture()){const raw=Buffer.alloc(8);d.ids.forEach((v,i)=>raw.writeUInt16LE(v,i*2));const data={ids:gzipSync(raw),core:Buffer.from(JSON.stringify(d.core)),places:Buffer.from(JSON.stringify({schemaVersion:1,places:[]}))};const assets={};for(const [key,bytes]of Object.entries(data))assets[key]={url:key,encoding:key==='ids'?'gzip':'json',byteLength:bytes.length,sha256:Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex'),...(key==='ids'?{decodedByteLength:8}:{})};const manifest={...d.manifest,format:'hgo-native-dataset',schemaVersion:1,coordinateSpace:{...d.manifest.coordinateSpace,kind:'pixel',origin:'top-left',wrapX:false},assets};return {manifest,data,fetchImpl:async url=>url.endsWith('manifest.json')?new Response(JSON.stringify(manifest)):new Response(data[url.split('/').at(-1)])};}
test('loader verifies transported hashes and little endian coverage',async()=>{const t=await transport(),d=await loadDataset('https://test.local/manifest.json',{fetchImpl:t.fetchImpl});assert.deepEqual([...d.ids],[1,2,0,3]);assert.equal(d.stateById.get('8').name,'Sea');t.manifest.assets.ids.sha256='0'.repeat(64);await assert.rejects(loadDataset('https://test.local/manifest.json',{fetchImpl:t.fetchImpl}),/integrity/);});
test('loader reports optional places failure and honors cancellation',async()=>{const t=await transport();t.manifest.assets.places.sha256='0'.repeat(64);const d=await loadDataset('https://test.local/manifest.json',{fetchImpl:t.fetchImpl});assert.match(d.placesWarning,/integrity/);assert.deepEqual(d.places,[]);const controller=new AbortController();controller.abort();await assert.rejects(loadDataset('https://test.local/manifest.json',{signal:controller.signal,fetchImpl:t.fetchImpl}),{name:'AbortError'});});
test('unused unassigned definition remains in table but may never occur in the raster',async()=>{const d=fixture();d.core.provinceIds.push(200);d.core.provinceStateIds.push(null);let t=await transport(d);const loaded=await loadDataset('https://test.local/manifest.json',{fetchImpl:t.fetchImpl});assert.equal(loaded.core.provinceIds[4],200);d.ids[2]=4;t=await transport(d);await assert.rejects(loadDataset('https://test.local/manifest.json',{fetchImpl:t.fetchImpl}),/missing province or state/);});
function sessionFixture(){
  const handlers=new Map();let serial=0,generation=0,error=0,lost=false;const deletions=[];
  const gl=new Proxy({NO_ERROR:0,getParameter:()=>8192,getShaderParameter:()=>true,getProgramParameter:()=>true,getError:()=>{const result=error;error=0;return result;},getExtension:()=>null,isContextLost:()=>lost},{get(target,key){if(key in target)return target[key];if(key.toUpperCase()===key)return ++serial;if(key.startsWith('create'))return ()=>({generation});if(key.startsWith('delete'))return object=>{deletions.push(object);if(!lost&&object.generation!==generation)error=1282;};return ()=>{};}});
  const win={devicePixelRatio:1,requestAnimationFrame:()=>1,cancelAnimationFrame(){},addEventListener(){},removeEventListener(){}};
  const canvas={clientWidth:600,clientHeight:300,width:600,height:300,ownerDocument:{defaultView:win},getContext:()=>gl,addEventListener:(name,fn)=>handlers.set(name,fn),removeEventListener:name=>handlers.delete(name),hasPointerCapture:()=>false};
  const overlayCanvas={width:600,height:300,getContext:()=>({clearRect(){}})};
  const errors=[];
  return {session:createHgoSession({canvas,overlayCanvas,dataset:fixture(),onError:error=>errors.push(error)}),handlers,errors,deletions,
    lose(){lost=true;handlers.get('webglcontextlost')({preventDefault(){}});},
    restore(){lost=false;generation++;error=0;handlers.get('webglcontextrestored')();}};
}
test('initial fit stays clean; user fit is saved view change and disposed session rejects actions',()=>{const {session,handlers}=sessionFixture();assert.equal(session.getViewModel().dirty,false);session.fit();assert.equal(session.getViewModel().dirty,true);session.markSaved();assert.equal(session.getViewModel().dirty,false);session.dispose();assert.equal(session.getViewModel().ready,false);assert.equal(handlers.size,0);assert.throws(()=>session.fit(),/disposed/);assert.throws(()=>session.paintStates([8],'#ffffff'),/disposed/);session.dispose();});
test('context loss preserves paint and history, restoration re-enables the session',()=>{const {session,handlers}=sessionFixture();session.paintStates([8],'#112233');let prevented=false;handlers.get('webglcontextlost')({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(session.getViewModel().ready,false);assert.equal(session.serializeDocument().paint[8],'#112233');handlers.get('webglcontextrestored')();assert.equal(session.getViewModel().ready,true);session.undo();assert.equal(session.serializeDocument().paint[8],undefined);session.dispose();});
test('restoration never deletes resources belonging to a lost WebGL generation',()=>{const {session,lose,restore,errors,deletions}=sessionFixture();session.paintStates([8],'#abcdef');for(let round=0;round<2;round++){lose();assert.equal(session.getViewModel().ready,false);restore();assert.equal(session.getViewModel().ready,true);assert.equal(session.serializeDocument().paint[8],'#abcdef');}assert.equal(errors.length,0);assert.equal(deletions.length,0);session.dispose();assert.ok(deletions.length>0);assert.ok(deletions.every(object=>object.generation===2));});
