// Add only the new product contracts; retain all prior route order and budgets.
export function createOwnershipRetirementRecords(existingRecords) {
  const start = Math.max(0, ...existingRecords.map(record => record.selectorOrder || 0)) + 1;
  return [{
    id: "node:test:node:ownership-retirement", commandRef: "test:node:ownership-retirement",
    sourceRefs: [
      "js/core/map_editing_policy.js", "js/core/map_data_boundary.js", "js/core/state/color_state.js",
      "js/core/map_renderer.js", "js/ui/dev_workspace.js",
      "js/core/color_resolver.js", "js/core/sovereignty_manager.js", "js/core/scenario_ownership_editor.js",
      "js/core/interaction_funnel/import_trust_projection.js", "js/core/state/actions/scenario_activation_actions.js",
      "js/core/state/actions/scenario_presentation_actions.js", "js/core/history_manager.js",
      "js/core/scenario/lifecycle_runtime.js", "js/core/interaction_funnel.js", "js/core/file_manager.js",
      "js/ui/sidebar.js", "js/ui/toolbar.js", "js/ui/dev_workspace/selection_ownership_controller.js",
      "js/ui/dev_workspace/scenario_tag_creator_controller.js", "js/ui/dev_workspace/dev_workspace_shell_builder.js",
      "js/ui/sidebar/scenario_inspector_controller.js", "js/ui/sidebar/country_inspector_controller.js",
      "js/core/quick_fill_hierarchy.js", "js/core/renderer/fill_target_policy.js",
      "js/core/renderer/color_resolution_strategy.js", "js/core/renderer/border_mesh_dynamic_runtime.js",
      "js/core/renderer/parent_border_grouping_policy.js", "js/core/palette_library_state_access.js",
      "js/core/scenario_runtime_queries.js", "js/core/legend_manager.js",
      "tests/reference_consumer_retirement.test.mjs", "tests/quick_fill_hierarchy.test.mjs",
      "tests/border_mesh_owner_behavior.test.mjs", "tests/border_draw_owner_behavior.test.mjs",
      "tests/palette_library_operation_behavior.test.mjs", "tests/palette_library_operation_boundary.test.mjs",
      "tests/parent_border_grouping_policy_behavior.test.mjs",
      "js/core/map_renderer/click_selection_transaction_owner.js", "js/core/renderer/brush_interaction_session_owner.js",
      "tests/click_selection_transaction_owner_behavior.test.mjs", "tests/visual_brush_transaction_behavior.test.mjs",
      "tests/fill_target_policy_behavior.test.mjs", "tests/brush_interaction_session_owner_behavior.test.mjs",
      "tests/scenario_hierarchy_behavior.test.mjs", "tests/legend_manager_generation_behavior.test.mjs",
      "tools/audit_quick_fill.mjs",
      "js/core/renderer/paint_contour_graph.js", "js/core/renderer/paint_contour_mesh.js",
      "js/core/renderer/paint_contour_runtime.js", "js/core/paint_contour_source.js",
      "js/core/scenario/chunk_layer_payloads.js", "js/core/scenario_chunk_manager.js", "js/core/renderer/political_collection_owner.js", "js/core/paint_contour_worker_client.js", "js/workers/paint_contour.worker.js",
      "js/core/renderer/border_draw_owner.js", "js/core/renderer/render_pass_signature_policy.js",
      "tests/paint_contour_graph_behavior.test.mjs", "tests/paint_contour_runtime_behavior.test.mjs",
      "tests/render_pass_signature_policy_behavior.test.mjs",
      "tests/map_data_boundary_behavior.test.mjs", "tests/ownership_retirement_behavior.test.mjs",
      "tests/dev_workspace_selection_ownership_behavior.test.mjs",
      "tools/verification/catalog/records/ownership_retirement.mjs",
    ],
    ownerHints: ["scenario-runtime"], domains: ["scenario-runtime"], tiers: ["contract"], cost: "fast",
    resourceLocks: [], executionOwners: ["child-safe"], profiles: ["pr-fast"], platforms: ["all"],
    entrypointPolicyIndex: 5, verificationOrder: null, selectorOrder: start, verification: null, selector: {},
  }, {
    id: "e2e:tests/e2e/ownership_retirement.spec.js",
    commandRef: "node tools/e2e_layering.mjs run-spec tests/e2e/ownership_retirement.spec.js",
    sourceRefs: ["tests/e2e/ownership_retirement.spec.js"],
    ownerHints: ["scenario-runtime"], domains: ["scenario-runtime"], tiers: ["regression"], cost: "heavy",
    resourceLocks: ["browser-dev-server", "playwright-browser", ".runtime-output"],
    executionOwners: ["main-thread"], profiles: ["full"], platforms: ["all"],
    entrypointPolicyIndex: 0, verificationOrder: null, selectorOrder: start + 1, verification: null, selector: {},
  }];
}
