// Internal catalog definitions. Consumers use verification_catalog_source.mjs.
export const PACKAGE_SCRIPTS = {
    "test:node:city-lights-assets": "node --test tests/city_lights_asset_contract.test.mjs",
    "test:node:city-lights-render-owner": "node --test tests/city_lights_render_owner_behavior.test.mjs",
    "test:node:modern-city-lights-owner": "npm run test:node:city-lights-render-owner",
    "test:node:day-night-runtime-owner": "node --test tests/day_night_runtime_owner_behavior.test.mjs",
    "test:node:data-service-runtime": "node --test tests/data_service_runtime_behavior.test.mjs",
    "test:node:intensity-field": "node --test tests/intensity_field.node.test.mjs",
    "test:node:intensity-field-mask": "node --test tests/intensity_field_mask_owner.node.test.mjs",
    "test:node:ocean-depth-layer-contracts": "node --test tests/ocean_depth_layer_contracts.test.mjs",
    "test:node:ocean-render-owner": "node --test tests/ocean_render_owner_behavior.test.mjs",
    "test:node:city-points-render-owner": "node --test tests/city_points_render_owner_behavior.test.mjs tests/urban_city_policy_strategic_values_behavior.test.mjs",
    "test:python:map-renderer-city-points-boundary": "npm run python -- -m unittest tests.test_map_renderer_urban_city_policy_boundary_contract tests.test_map_renderer_city_label_owner_boundary_contract -q",
    "test:node:appearance-city-points-owner": "node --test tests/appearance_city_points_owner_behavior.test.mjs",
    "test:node:appearance-border-owner": "node --test tests/appearance_border_owner_behavior.test.mjs",
    "test:node:appearance-parent-border-owner": "node --test tests/appearance_parent_border_owner_behavior.test.mjs",
    "test:node:appearance-physical-owner": "node --test tests/appearance_physical_owner_behavior.test.mjs",
    "test:node:appearance-presets": "node --test tests/appearance_preset_state.node.test.mjs tests/appearance_presets_owner_behavior.test.mjs tests/appearance_preset_history.node.test.mjs",
    "test:node:appearance-transport-change-set": "node --test tests/appearance_transport_change_set_contract_behavior.test.mjs tests/appearance_transport_operation_behavior.test.mjs",
    "test:node:appearance-reference-owner": "node --test tests/appearance_reference_owner_behavior.test.mjs",
    "test:node:appearance-rivers-owner": "node --test tests/appearance_rivers_owner_behavior.test.mjs",
    "test:node:appearance-texture-owner": "node --test tests/appearance_texture_owner_behavior.test.mjs",
    "test:node:layer-panel-contracts": "node --test tests/layer_panel_contracts_behavior.test.mjs",
    "test:node:layer-status-diagnostics": "node --test tests/layer_status_diagnostics_behavior.test.mjs",
    "test:node:thematic-layer-catalog": "node --test tests/thematic_layer_catalog_behavior.test.mjs tests/thematic_layer_preview_controller_behavior.test.mjs",
    "test:node:thematic-admin-metrics-loader": "node --test tests/thematic_admin_metrics_loader_behavior.test.mjs",
    "test:node:toolbar-render-scheduler": "node --test tests/toolbar_render_scheduler_behavior.test.mjs",
    "test:node:post-ready-scheduler": "node --test tests/post_ready_scheduler_behavior.test.mjs tests/main_post_ready_scheduler_boundary.test.mjs",
    "test:node:main-runtime-diagnostics": "node --test tests/main_runtime_diagnostics_behavior.test.mjs tests/main_runtime_diagnostics_boundary.test.mjs",
    "test:node:render-runtime-binding": "node --test tests/render_runtime_binding_behavior.test.mjs tests/main_render_runtime_binding_boundary.test.mjs",
    "test:node:startup-failure-recovery": "node --test tests/startup_failure_recovery_behavior.test.mjs tests/main_startup_failure_recovery_boundary.test.mjs",
    "test:node:ui-shell-boot": "node --test tests/ui_shell_boot_behavior.test.mjs tests/main_ui_shell_boot_boundary.test.mjs",
    "test:node:deferred-bootstrap": "node --test tests/deferred_vendor_loader_behavior.test.mjs tests/deferred_ui_bootstrap_behavior.test.mjs tests/main_deferred_bootstrap_boundary.test.mjs",
    "test:node:main-bootstrap-wiring": "node --test tests/main_bootstrap_wiring_boundary.test.mjs",
    "test:node:startup-ready-handoff": "node --test tests/startup_ready_handoff_behavior.test.mjs tests/main_startup_ready_handoff_boundary.test.mjs",
    "test:node:startup-resource-graph": "node --test tests/startup_resource_graph_contract.test.mjs",
    "python": "node tools/run_python.mjs",
    "test:node:backend-cloud-support": "node --test tests/backend_client_behavior.test.mjs tests/project_support_diagnostics_controller_behavior.test.mjs tests/backend_console_helpers.test.mjs",
    "test:node:backend-console-helpers": "node --test tests/backend_console_helpers.test.mjs",
    "start:backend-preview": "npm run python -- tools/dev_server.py /backend/",
    "verify:backend-preview": "npm run test:py:backend-cloud-support && node --test tests/backend_client_behavior.test.mjs tests/backend_console_helpers.test.mjs && node --check backend/app.js backend/backend_console_helpers.js js/api/backend_client.js tools/run_python.mjs",
    "test:node:transport-appearance-controller": "node --test tests/transport_appearance_controller_behavior.test.mjs",
    "test:node:transport-facility-render-owner": "node --test tests/transport_facility_render_owner_behavior.test.mjs",
    "test:node:transport-workbench-controller": "npm run test:node:transport-workbench-event-owner && npm run test:node:transport-workbench-shell-owner",
    "test:node:transport-workbench-event-owner": "node --test tests/transport_workbench_event_owner_behavior.test.mjs",
    "test:node:transport-workbench-shell-owner": "node --test tests/transport_workbench_shell_owner_behavior.test.mjs",
    "test:node:transport-workbench-inspector-owner": "node --test tests/transport_workbench_inspector_owner_behavior.test.mjs",
    "test:node:transport-workbench-layer-order-owner": "node --test tests/transport_workbench_layer_order_owner_behavior.test.mjs",
    "test:node:transport-workbench-lens-owner": "node --test tests/transport_workbench_lens_owner_behavior.test.mjs",
    "test:node:transport-workbench-popover-owner": "node --test tests/transport_workbench_popover_owner_behavior.test.mjs",
    "test:node:transport-workbench-preview-lifecycle-owner": "node --test tests/transport_workbench_preview_lifecycle_owner_behavior.test.mjs tests/transport_workbench_line_runtime_shared_behavior.test.mjs tests/transport_workbench_road_preview_runtime_behavior.test.mjs tests/transport_workbench_rail_preview_runtime_behavior.test.mjs",
    "test:node:transport-workbench-right-deck-owner": "node --test tests/transport_workbench_right_deck_owner_behavior.test.mjs",
    "test:node:transport-workbench-state-owner": "node --test tests/transport_workbench_state_owner_behavior.test.mjs",
    "test:py:backend-cloud-support": "npm run python -- -m unittest tests.test_backend_service tests.test_backend_routes -q",
    "start:ui-shell": "npm run python -- tools/dev_server.py \"/app/?ui_shell=1&startup_interaction=full&startup_worker=0&startup_cache=0\"",
    "build:transport-workbench-carrier": "npm run python -- tools/build_transport_workbench_japan_carrier.py",
    "build:transport-workbench-japan-roads": "npm run python -- tools/build_transport_workbench_japan_roads.py",
    "build:transport-workbench-japan-rail": "npm run python -- tools/build_transport_workbench_japan_rail.py",
    "build:transport-workbench-japan-airports": "npm run python -- tools/build_transport_workbench_japan_airports.py",
    "build:transport-workbench-japan-ports": "npm run python -- tools/build_transport_workbench_japan_ports.py",
    "playwright:install": "playwright install",
    "playwright:install:chromium": "playwright install --with-deps chromium",
    "verify:ui-contract-foundation": "npm run python -- -m unittest tests/test_ui_rework_plan01_foundation_contract.py",
    "verify:toolbar-split-boundary": "npm run python -- -m unittest tests.test_toolbar_split_boundary_contract -q",
    "verify:state-write-allowlist": "node tools/check_state_write_allowlist.mjs",
    "test:node:p4:state-writer-policy": "node tools/run_p4_state_writer_policy_tests.mjs",
    "test:node:p4:state-writer-policy:quick": "node tools/run_p4_state_writer_policy_tests.mjs --quick",
    "verify:p4:state-writer-policy": "npm run test:node:p4:state-writer-policy && node tools/check_state_writer_policy.mjs",
    "test:python:p4:state-write-boundary": "node tools/run_p4_state_write_boundary.mjs",
    "test:node:p4:phase-verification-runner": "node --test tests/p4_phase_verification_runner_behavior.test.mjs",
    "test:node:p4:p4-1": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/boot_actions_behavior.test.mjs tests/startup_boot_overlay_behavior.test.mjs tests/startup_bootstrap_support_behavior.test.mjs tests/post_ready_scheduler_behavior.test.mjs tests/ui_shell_boot_behavior.test.mjs tests/startup_hydration_behavior.test.mjs tests/sample_project_contracts.test.mjs tests/state_writer_scanner_soundness_behavior.test.mjs",
    "test:python:p4:p4-1-boundary": "npm run python -- -m unittest tests.test_boot_state_actions_boundary_contract tests.test_state_split_boundary_contract tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-1": "node tools/run_p4_phase_verification.mjs --phase P4.1",
    "test:node:scenario-state-actions-atomicity": "node --test tests/scenario_state_actions_atomicity_behavior.test.mjs",
    "test:node:p4:p4-2a": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/state_action_delegation_edges_behavior.test.mjs tests/state_writer_policy_batch_scan_behavior.test.mjs tests/scenario_state_actions_atomicity_behavior.test.mjs tests/scenario_transaction_rollback_actions_behavior.test.mjs tests/scenario_apply_transaction_ownership.test.mjs tests/scenario_lifecycle_runtime_behavior.test.mjs tests/scenario_runtime_state_behavior.test.mjs",
    "test:python:p4:p4-2a-boundary": "npm run python -- -m unittest tests.test_scenario_state_actions_boundary_contract tests.test_scenario_manager_boundary_contract tests.test_scenario_resources_boundary_contract tests.test_scenario_rollback_boundary_contract tests.test_scenario_lifecycle_runtime_boundary_contract tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-2a": "node tools/run_p4_phase_verification.mjs --phase P4.2a",
    "test:node:p4:p4-2b": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/state_action_delegation_edges_behavior.test.mjs tests/state_writer_policy_batch_scan_behavior.test.mjs tests/scenario_chunk_state_actions_behavior.test.mjs tests/scenario_chunk_contracts.test.mjs tests/scenario_chunk_promotion_helpers_behavior.test.mjs tests/scenario_refresh_plans_behavior.test.mjs tests/scenario_runtime_state_behavior.test.mjs tests/scenario_state_actions_atomicity_behavior.test.mjs tests/scenario_transaction_rollback_actions_behavior.test.mjs tests/scenario_lifecycle_runtime_behavior.test.mjs",
    "test:python:p4:p4-2b-boundary": "npm run python -- -m unittest tests.test_scenario_chunk_state_actions_boundary_contract tests.test_scenario_chunk_refresh_contracts tests.test_main_deferred_detail_promotion_boundary_contract tests.test_scenario_manager_boundary_contract tests.test_scenario_rollback_boundary_contract tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-2b": "node tools/run_p4_phase_verification.mjs --phase P4.2b",
    "test:node:p4:p4-2c": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/state_action_delegation_edges_behavior.test.mjs tests/state_writer_policy_batch_scan_behavior.test.mjs tests/scenario_health_actions_behavior.test.mjs tests/startup_hydration_behavior.test.mjs tests/scenario_lifecycle_runtime_behavior.test.mjs tests/scenario_runtime_state_behavior.test.mjs tests/scenario_state_actions_atomicity_behavior.test.mjs tests/scenario_transaction_rollback_actions_behavior.test.mjs",
    "test:python:p4:p4-2c-boundary": "npm run python -- -m unittest tests.test_scenario_health_actions_boundary_contract tests.test_startup_hydration_boundary_contract tests.test_scenario_data_health_boundary_contract tests.test_scenario_presentation_runtime_boundary_contract tests.test_scenario_lifecycle_runtime_boundary_contract tests.test_scenario_rollback_boundary_contract tests.test_scenario_runtime_state_boundary_contract tests.test_scenario_state_actions_boundary_contract tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-2c": "node tools/run_p4_phase_verification.mjs --phase P4.2c",
    "test:node:p4:p4-3": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/state_action_delegation_edges_behavior.test.mjs tests/state_writer_policy_batch_scan_behavior.test.mjs tests/renderer_phase_actions_behavior.test.mjs tests/renderer_interaction_actions_behavior.test.mjs tests/renderer_exact_refresh_actions_behavior.test.mjs tests/render_pass_cache_state_normalizer_behavior.test.mjs tests/renderer_cache_actions_behavior.test.mjs tests/renderer_diagnostics_actions_behavior.test.mjs tests/render_snapshot_behavior.test.mjs tests/render_perf_metrics_runtime_owner_behavior.test.mjs tests/day_night_runtime_owner_behavior.test.mjs tests/visual_effects_pass_owner_behavior.test.mjs tests/political_background_render_owner_behavior.test.mjs tests/exact_after_settle_scheduler_state_actions_behavior.test.mjs tests/renderer_render_phase_lifecycle_inventory.test.mjs tests/renderer_render_phase_lifecycle_owner_behavior.test.mjs tests/zoom_interaction_lifecycle_owner_behavior.test.mjs tests/renderer_runtime_state_behavior.test.mjs tests/physical_layer_contracts.test.mjs tests/scenario_chunk_contracts.test.mjs",
    "test:python:p4:p4-3-boundary": "npm run python -- -m unittest tests.test_renderer_control_actions_boundary_contract tests.test_renderer_exact_refresh_actions_boundary_contract tests.test_renderer_cache_actions_boundary_contract tests.test_renderer_diagnostics_actions_boundary_contract tests.test_map_renderer_render_snapshot_boundary_contract tests.test_day_night_runtime_owner_boundary_contract tests.test_map_renderer_political_background_render_owner_boundary_contract tests.test_renderer_runtime_state_boundary_contract tests.test_scenario_chunk_refresh_contracts tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-3": "node tools/run_p4_phase_verification.mjs --phase P4.3",
    "test:node:p4:p4-4": "node --test tests/p4_phase_verification_runner_behavior.test.mjs tests/state_action_delegation_edges_behavior.test.mjs tests/state_writer_policy_batch_scan_behavior.test.mjs tests/appearance_actions_behavior.test.mjs tests/appearance_preset_actions_behavior.test.mjs tests/appearance_preset_history.node.test.mjs tests/appearance_preset_state.node.test.mjs tests/appearance_reference_actions_behavior.test.mjs tests/appearance_selection_actions_behavior.test.mjs tests/appearance_state_action_callers_behavior.test.mjs tests/appearance_visibility_actions_behavior.test.mjs tests/intensity_field_actions_behavior.test.mjs tests/export_workbench_actions_behavior.test.mjs tests/transport_actions_behavior.test.mjs tests/transport_workbench_state_owner_behavior.test.mjs tests/ui_chrome_actions_behavior.test.mjs tests/ui_dirty_actions_behavior.test.mjs tests/ui_visibility_actions_behavior.test.mjs tests/ui_state_action_callers_behavior.test.mjs tests/strategic_overlay_actions_behavior.test.mjs tests/special_zone_actions_behavior.test.mjs tests/special_zones_workbench_controller_behavior.test.mjs tests/strategic_overlay_runtime_owner_behavior.test.mjs",
    "test:python:p4:p4-4-boundary": "npm run python -- -m unittest tests.test_state_write_guardrail_contract -q",
    "verify:p4:p4-4": "node tools/run_p4_phase_verification.mjs --phase P4.4",
    "verify:p4:routes": "node tools/check_p4_state_action_routes.mjs",
    "verify:ui-rework-mainline": "npm run python -- -m unittest tests/test_ui_rework_plan02_mainline_contract.py",
    "verify:ui-rework-support": "npm run python -- -m unittest tests/test_ui_rework_plan03_support_transport_contract.py",
    "verify:scenario-contracts": "npm run python -- tools/check_scenario_contracts.py --scenario-dir data/scenarios/tno_1962",
    "verify:scenario-contracts:strict": "npm run python -- tools/check_scenario_contracts.py --strict --scenario-dir data/scenarios/tno_1962 --report-path .runtime/reports/generated/tno_1962.strict_contract_report.json",
    "verify:tno-coverage-ledger": "npm run python -- tools/check_scenario_contracts.py --strict --scenario-dir data/scenarios/tno_1962 --report-path .runtime/reports/generated/tno_1962.coverage_ledger_report.json",
    "verify:tno-atlantropa-coverage": "npm run python -- tools/check_scenario_contracts.py --strict --scenario-dir data/scenarios/tno_1962 --report-path .runtime/reports/generated/tno_1962.atlantropa_coverage_report.json",
    "verify:tno-polar-coverage": "npm run python -- tools/validate_tno_water_geometries.py --scenario-dir data/scenarios/tno_1962 --report-path .runtime/reports/generated/tno_1962.polar_coverage_report.json",
    "verify:tno-coverage-chain": "npm run python -- tools/check_scenario_contracts.py --strict --scenario-dir data/scenarios/tno_1962 --report-path .runtime/reports/generated/tno_1962.strict_contract_report.json --report-path .runtime/reports/generated/tno_1962.coverage_ledger_report.json --report-path .runtime/reports/generated/tno_1962.atlantropa_coverage_report.json && npm run verify:tno-polar-coverage && npm run test:node:scenario-chunk-contracts",
    "build:hgo-scenario": "npm run python -- tools/build_hgo_scenario.py",
    "verify:scenario-contracts:hgo": "npm run python -- tools/check_scenario_contracts.py --strict --scenario-dir data/scenarios/hgo_1936 --report-path .runtime/reports/generated/hgo_1936.strict_contract_report.json",
    "test:py:tno-water-repair-contracts": "npm run python -- -m unittest tests.test_tno_water_owners_consistency tests.test_tno_bundle_builder.TnoBundleBuilderTest.test_run_changed_domain_plan_for_water_repairs_contract_outputs_after_chunks tests.test_tno_bundle_builder.TnoBundleBuilderTest.test_external_publish_checkpoint_validation_uses_tno_profile_and_hard_fails_final_files tests.test_tno_bundle_builder.TnoBundleBuilderTest.test_prechunk_publish_checkpoint_validation_only_allows_missing_build_snapshot tests.test_tno_bundle_builder.TnoBundleBuilderTest.test_write_bundle_stage_blocks_publish_when_strict_checkpoint_validation_fails -q",
    "perf:baseline": "node tools/perf/run_baseline.mjs --mode baseline --scenarios tno_1962,hoi4_1939 --runs 5 --warmups 3",
    "perf:gate": "node tools/perf/run_baseline.mjs --mode gate --scenarios tno_1962,hoi4_1939 --runs 5 --warmups 3 --threshold 1.15 --write-markdown false",
    "perf:analyze-render-sample-roles": "node tools/perf/analyze_render_sample_roles.mjs",
    "test:node:render-sample-role-policy": "node --test tests/render_sample_role_policy_behavior.test.mjs tests/perf_role_governed_report_behavior.test.mjs",
    "perf:williams-crossover:plan": "node tools/perf/run_williams_crossover.mjs --plan",
    "perf:williams-crossover:analyze": "node tools/perf/run_williams_crossover.mjs --analyze",
    "perf:williams-crossover:run": "node tools/perf/run_williams_crossover.mjs --execute",
    "test:node:williams-crossover-governance": "node --test tests/williams_crossover_governance_behavior.test.mjs",
    "test:node:williams-crossover-job-runner": "node --test tests/williams_crossover_windows_job_runner_behavior.test.mjs tests/williams_crossover_windows_job_runner_integration.test.mjs",
    "test:node:windows-job-runtime": "node --test tests/windows_job_runner_v2_native_contract.test.mjs tests/windows_job_runtime_behavior.test.mjs",
    "test:node:windows-job-runtime:integration": "node --test tests/windows_job_runtime_integration.test.mjs",
    "test:node:williams-crossover-telemetry-live": "node -e \"process.env.WILLIAMS_LIVE_TELEMETRY_TEST='1'; import('./tests/williams_crossover_windows_job_runner_integration.test.mjs')\"",
    "perf:williams-power-scheme:live-preflight": "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File tools/perf/williams_crossover_power_scheme.ps1 -LivePreflight",
    "test:e2e:ui-contract-foundation": "node node_modules/@playwright/test/cli.js test tests/e2e/ui_contract_foundation.spec.js --workers=1 --retries=0",
    "test:e2e:ui-rework-mainline": "node node_modules/@playwright/test/cli.js test tests/e2e/ui_rework_mainline_shell_sidebar.spec.js --workers=1 --retries=0",
    "test:e2e:ui-rework-support": "node node_modules/@playwright/test/cli.js test tests/e2e/ui_rework_support_transport_hardening.spec.js --workers=1 --retries=0",
    "test:e2e": "node node_modules/@playwright/test/cli.js test",
    "test:node:renderer-splits": "node --test tests/transient_overlay_render_owner_behavior.test.mjs tests/unit_counter_display_model_behavior.test.mjs tests/operation_graphic_geometry_behavior.test.mjs tests/strategic_overlay_runtime_owner_behavior.test.mjs tests/strategic_overlay_render_owner_behavior.test.mjs tests/retired_frontline_behavior.test.mjs tests/strategic_overlay_state_behavior.test.mjs tests/special_zone_layers_state_behavior.test.mjs tests/special_zones_workbench_controller_behavior.test.mjs tests/scenario_optional_layers_behavior.test.mjs",
    "test:node:annotation-productization": "node --test tests/file_manager_project_roundtrip_behavior.test.mjs tests/export_workbench_state_behavior.test.mjs tests/strategic_overlay_runtime_owner_behavior.test.mjs",
    "test:node:scenario-lifecycle-runtime-behavior": "node --test tests/scenario_lifecycle_runtime_behavior.test.mjs",
    "test:node:scenario-runtime-state-behavior": "node --test tests/scenario_runtime_state_behavior.test.mjs",
    "test:node:scenario-apply-transaction-ownership": "node --test tests/scenario_apply_transaction_ownership.test.mjs",
    "test:node:scenario-context-bar-controller": "node --test tests/scenario_context_bar_controller_behavior.test.mjs",
    "test:node:worker-task-client": "node --test tests/worker_task_client_behavior.test.mjs",
    "test:node:spatial-query-index": "node --test tests/spatial_query_index_behavior.test.mjs",
    "test:node:scenario-chunk-promotion-helpers": "node --test tests/scenario_chunk_promotion_helpers_behavior.test.mjs",
    "test:node:scenario-refresh-plans": "node --test tests/scenario_refresh_plans_behavior.test.mjs tests/scenario_visual_invalidation_executor_behavior.test.mjs",
    "test:node:exact-after-settle-refresh-plans": "node --test tests/exact_after_settle_refresh_plans_behavior.test.mjs",
    "test:node:exact-after-settle-pass-catalog": "node --test tests/exact_after_settle_pass_catalog_behavior.test.mjs",
    "test:node:interaction-hit-candidates": "node --test tests/interaction_hit_candidates_behavior.test.mjs",
    "test:node:startup-hydration-behavior": "node --test tests/startup_hydration_behavior.test.mjs",
    "test:node:dev-workspace-selection-ownership": "node --test tests/dev_workspace_selection_ownership_behavior.test.mjs",
    "test:node:hgo-identity-resolver": "node --test tests/hgo_identity_resolver.node.test.mjs",
    "test:node:hgo-runtime-index": "node --test tests/hgo_runtime_index.node.test.mjs",
    "test:node:hgo-projection-model": "node --test tests/hgo_projection_model.node.test.mjs",
    "test:node:hgo-raster-renderer": "node --test tests/hgo_raster_renderer.node.test.mjs",
    "test:node:hgo-runtime-preview": "node --test tests/hgo_runtime_preview.node.test.mjs tests/hgo_runtime_preview_toolbar.node.test.mjs",
    "test:py:hgo-runtime-seed": "npm run python -- -m unittest tests.test_hgo_runtime_seed_builder -q",
    "test:py:hgo-runtime-assets": "npm run python -- -m unittest tests.test_hgo_runtime_seed_builder -q",
    "test:py:hgo-runtime-assets-contract": "npm run python -- -m unittest tests.test_data_manifest_contract tests.test_data_catalog_contract -q",
    "test:py:thematic-layer-contracts": "npm run python -- -m unittest tests.test_thematic_layer_contracts tests.test_thematic_wgi_source_ingest -q",
    "smoke:hgo-runtime-source": "npm run python -- tools/build_hgo_runtime_seed.py",
    "build:hgo-runtime-assets": "npm run python -- tools/build_hgo_runtime_assets.py",
    "spike:hgo-runtime-lod": "node tools/spike_hgo_runtime_lod_assets.mjs",
    "verify:hgo-runtime-poc": "npm run test:py:hgo-runtime-assets && npm run test:node:hgo-runtime-index && npm run test:node:hgo-projection-model && npm run test:node:hgo-raster-renderer && npm run test:node:hgo-runtime-preview && npm run test:py:hgo-runtime-assets-contract && node --check js/core/hgo_runtime_index.js js/core/hgo_projection_model.js js/core/hgo_raster_renderer.js js/core/hgo_runtime_asset_loader.js js/core/hgo_runtime_preview.js js/ui/toolbar.js js/ui/toolbar/hgo_runtime_preview_controller.js && npm run python -- -m py_compile tools/build_hgo_runtime_seed.py tools/build_hgo_runtime_assets.py",
    "test:node:country-inspector-controller": "node --test tests/country_inspector_controller_behavior.test.mjs",
    "test:node:sidebar-hgo-identity-startup": "node --test tests/sidebar_hgo_identity_startup_behavior.test.mjs",
    "test:node:palette-runtime-bridge": "node --test tests/palette_runtime_bridge.node.test.mjs",
    "test:node:legend-generation": "node --test tests/legend_manager_generation_behavior.test.mjs",
    "test:node:political-collection-fragment-camouflage": "node --test tests/political_collection_fragment_camouflage_behavior.test.mjs",
    "test:node:transport-overview-line-contract": "node --test tests/transport_overview_line_strategy_scope_contract.node.test.mjs",
    "test:node:renderer-host-inventory": "node --test tests/renderer_host_inventory_boundary.test.mjs",
    "test:node:renderer-surface-host": "node --test tests/renderer_surface_host_behavior.test.mjs tests/renderer_surface_host_inventory_boundary.test.mjs",
    "test:node:renderer-surface-host-inventory": "node --test tests/renderer_surface_host_inventory_boundary.test.mjs",
    "test:node:renderer-surface-runtime-bridge-state": "node --test tests/renderer_surface_runtime_bridge_state_behavior.test.mjs",
    "test:node:renderer-surface-lifecycle-inventory": "node --test tests/renderer_surface_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-surface-lifecycle-owner": "node --test tests/renderer_surface_lifecycle_owner_behavior.test.mjs",
    "test:node:renderer-surface-lifecycle": "node --test tests/renderer_surface_lifecycle_owner_behavior.test.mjs tests/renderer_surface_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-projection-path-owner": "node --test tests/renderer_projection_path_owner_behavior.test.mjs",
    "test:node:renderer-projection-path-lifecycle-inventory": "node --test tests/renderer_projection_path_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-projection-path-lifecycle": "node --test tests/renderer_projection_path_owner_behavior.test.mjs tests/renderer_projection_path_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-projection-contract": "node --test tests/renderer_projection_contract_inventory.test.mjs",
    "test:node:renderer-svg-surface-lifecycle-owner": "node --test tests/renderer_svg_surface_lifecycle_owner_behavior.test.mjs",
    "test:node:renderer-svg-surface-lifecycle-inventory": "node --test tests/renderer_svg_surface_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-svg-surface-lifecycle": "node --test tests/renderer_svg_surface_lifecycle_owner_behavior.test.mjs tests/renderer_svg_surface_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-fit-projection-owner": "node --test tests/renderer_fit_projection_owner_behavior.test.mjs",
    "test:node:renderer-fit-projection-lifecycle-inventory": "node --test tests/renderer_fit_projection_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-fit-projection-lifecycle": "node --test tests/renderer_fit_projection_owner_behavior.test.mjs tests/renderer_fit_projection_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-viewport-update-owner": "node --test tests/renderer_viewport_update_owner_behavior.test.mjs",
    "test:node:renderer-startup-transaction-owner": "node --test tests/renderer_startup_transaction_owner_behavior.test.mjs",
    "test:node:renderer-startup-transaction-inventory": "node --test tests/renderer_startup_transaction_inventory_boundary.test.mjs",
    "test:node:renderer-set-map-data-transaction-owner": "node --test tests/renderer_set_map_data_transaction_owner_behavior.test.mjs",
    "test:node:renderer-set-map-data-transaction-inventory": "node --test tests/renderer_set_map_data_transaction_inventory_boundary.test.mjs",
    "test:node:renderer-set-map-data-transaction": "npm run test:node:renderer-set-map-data-transaction-owner && npm run test:node:renderer-set-map-data-transaction-inventory",
    "test:node:renderer-transaction-reset-owner": "node --test tests/renderer_transaction_reset_owner_behavior.test.mjs",
    "test:node:renderer-transaction-reset-hardening-inventory": "node --test tests/renderer_transaction_reset_hardening_inventory_boundary.test.mjs",
    "test:node:renderer-transaction-reset": "npm run test:node:renderer-transaction-reset-owner && npm run test:node:renderer-transaction-reset-hardening-inventory",
    "test:node:renderer-render-lifecycle-inventory": "node --test tests/renderer_render_lifecycle_inventory_boundary.test.mjs",
    "test:node:renderer-render-pass-cache-host-inventory": "node --test tests/renderer_render_pass_cache_host_inventory_boundary.test.mjs",
    "test:node:render-pass-cache-host-owner": "node --test tests/render_pass_cache_host_owner_behavior.test.mjs",
    "test:node:render-pass-cache-host-owner-inventory": "node --test tests/render_pass_cache_host_owner_inventory.test.mjs",
    "test:node:render-pass-cache-host-owner-suite": "npm run test:node:render-pass-cache-host-owner && npm run test:node:render-pass-cache-host-owner-inventory && npm run test:node:renderer-render-pass-cache-host-inventory",
    "test:node:render-pass-commit-accounting-owner": "node --test tests/render_pass_commit_accounting_owner_behavior.test.mjs",
    "test:node:render-pass-commit-accounting-inventory": "node --test tests/render_pass_commit_accounting_owner_inventory.test.mjs",
    "test:node:render-pass-commit-accounting-owner-suite": "npm run test:node:render-pass-commit-accounting-owner && npm run test:node:render-pass-commit-accounting-inventory",
    "test:python:map-renderer-render-cache-owner-boundary": "npm run python -- -m unittest tests.test_map_renderer_render_cache_owner_boundary_contract -q",
    "test:python:day-night-runtime-owner-boundary": "npm run python -- -m unittest tests.test_day_night_runtime_owner_boundary_contract -q",
    "test:python:map-renderer-projection-viewport-context-boundary": "npm run python -- -m unittest tests.test_map_renderer_projection_viewport_context_boundary_contract -q",
    "test:python:map-renderer-viewport-mutation-context-boundary": "npm run python -- -m unittest tests.test_map_renderer_viewport_mutation_context_boundary_contract -q",
    "test:python:map-renderer-interaction-context-boundary": "npm run python -- -m unittest tests.test_map_renderer_interaction_context_boundary_contract -q",
    "test:python:map-renderer-hit-hover-context-boundary": "npm run python -- -m unittest tests.test_map_renderer_hit_hover_context_boundary_contract -q",
    "test:node:renderer-draw-canvas-orchestration-inventory": "node --test tests/renderer_draw_canvas_orchestration_inventory_boundary.test.mjs",
    "test:node:draw-canvas-orchestration-owner": "node --test tests/draw_canvas_orchestration_owner_behavior.test.mjs",
    "test:node:draw-canvas-orchestration-owner-suite": "npm run test:node:draw-canvas-orchestration-owner && npm run test:node:renderer-draw-canvas-orchestration-inventory && npm run test:python:map-renderer-draw-canvas-orchestration-boundary",
    "test:python:map-renderer-draw-canvas-orchestration-boundary": "npm run python -- -m unittest tests.test_map_renderer_draw_canvas_orchestration_owner_boundary_contract -q",
    "test:node:cached-pass-compositor-owner": "node --test tests/cached_pass_compositor_owner_behavior.test.mjs",
    "test:node:cached-pass-compositor-owner-suite": "npm run test:node:cached-pass-compositor-owner && npm run test:node:renderer-draw-canvas-orchestration-inventory && npm run test:python:map-renderer-frame-compositor-boundary",
    "test:node:transformed-frame-compositor-owner": "node --test tests/transformed_frame_compositor_owner_behavior.test.mjs",
    "test:node:transformed-frame-compositor-owner-suite": "npm run test:node:transformed-frame-compositor-owner && npm run test:node:renderer-draw-canvas-orchestration-inventory && npm run test:python:map-renderer-frame-compositor-boundary",
    "test:python:map-renderer-frame-compositor-boundary": "npm run python -- -m unittest tests.test_map_renderer_frame_compositor_owner_boundary_contract -q",
    "test:node:click-selection-transaction-owner": "node --test tests/click_selection_transaction_owner_behavior.test.mjs",
    "test:node:renderer-click-selection-transaction-inventory": "node --test tests/renderer_click_selection_transaction_inventory_boundary.test.mjs",
    "test:python:map-renderer-click-selection-transaction-boundary": "npm run python -- -m unittest tests.test_map_renderer_click_selection_transaction_boundary_contract -q",
    "test:node:renderer-render-request-boundary-owner": "node --test tests/renderer_render_request_boundary_owner_behavior.test.mjs",
    "test:node:renderer-render-request-boundary-inventory": "node --test tests/renderer_render_request_boundary_inventory.test.mjs",
    "test:node:renderer-render-request-boundary": "npm run test:node:renderer-render-request-boundary-owner && npm run test:node:renderer-render-request-boundary-inventory",
    "test:node:renderer-render-phase-lifecycle-owner": "node --test tests/renderer_render_phase_lifecycle_owner_behavior.test.mjs",
    "test:node:renderer-render-phase-lifecycle-inventory": "node --test tests/renderer_render_phase_lifecycle_inventory.test.mjs",
    "test:node:renderer-render-phase-lifecycle": "npm run test:node:renderer-render-phase-lifecycle-owner && npm run test:node:renderer-render-phase-lifecycle-inventory",
    "test:node:hit-canvas-scheduling-owner": "node --test tests/hit_canvas_scheduling_owner_behavior.test.mjs",
    "test:node:hit-canvas-scheduling-owner-inventory": "node --test tests/hit_canvas_scheduling_owner_inventory.test.mjs",
    "test:node:hit-canvas-scheduling-owner-suite": "npm run test:node:hit-canvas-scheduling-owner && npm run test:node:hit-canvas-scheduling-owner-inventory && node --test tests/renderer_hit_canvas_scheduling_inventory_boundary.test.mjs",
    "test:node:map-hover-interaction-owner": "node --test tests/map_hover_interaction_owner_behavior.test.mjs",
    "test:node:map-hover-interaction-inventory": "node --test tests/map_hover_interaction_owner_inventory.test.mjs",
    "test:node:map-hover-interaction": "npm run test:node:map-hover-interaction-owner && npm run test:node:map-hover-interaction-inventory",
    "test:node:visible-frame-diagnostics-owner": "node --test tests/visible_frame_diagnostics_owner_behavior.test.mjs",
    "test:node:visible-frame-diagnostics-inventory": "node --test tests/visible_frame_diagnostics_owner_inventory.test.mjs",
    "test:node:visible-frame-diagnostics": "npm run test:node:visible-frame-diagnostics-owner && npm run test:node:visible-frame-diagnostics-inventory",
    "test:node:render-cache-owner": "node --test tests/render_cache_owner_invalidation_behavior.test.mjs",
    "test:node:render-transform-reuse-policy-owner": "node --test tests/render_transform_reuse_policy_owner_behavior.test.mjs",
    "test:node:projected-geometry-bounds-owner": "node --test tests/projected_geometry_bounds_owner_behavior.test.mjs",
    "test:node:viewport-read-model-owner": "node --test tests/viewport_read_model_owner_behavior.test.mjs",
    "test:node:viewport-command-owner": "node --test tests/viewport_command_owner_behavior.test.mjs",
    "test:node:viewport-resize-lifecycle-owner": "node --test tests/viewport_resize_lifecycle_owner_behavior.test.mjs",
    "test:node:zoom-interaction-lifecycle-owner": "node --test tests/zoom_interaction_lifecycle_owner_behavior.test.mjs",
    "test:node:strategic-overlay-runtime-owner": "node --test tests/strategic_overlay_runtime_owner_behavior.test.mjs",
    "test:node:map-interaction-event-binding-owner": "node --test tests/map_interaction_event_binding_owner_behavior.test.mjs",
    "test:node:scenario-water-cache-policy-owner": "node --test tests/scenario_water_cache_policy_owner_behavior.test.mjs",
    "test:node:render-pass-catalog": "node --test tests/render_pass_catalog_behavior.test.mjs",
    "test:node:render-pipeline-catalog": "node --test tests/render_pipeline_catalog_behavior.test.mjs",
    "test:node:render-invalidation-catalog": "node --test tests/render_invalidation_catalog_behavior.test.mjs",
    "test:node:renderer-runtime-state-behavior": "node --test tests/renderer_runtime_state_behavior.test.mjs",
    "test:node:render-transaction-diagnostics": "node --test tests/render_transaction_diagnostics_behavior.test.mjs",
    "test:node:border-draw-owner-behavior": "node --test tests/border_draw_owner_behavior.test.mjs",
    "test:node:border-mesh-owner-behavior": "node --test tests/border_mesh_owner_behavior.test.mjs",
    "test:node:canvas-layer-manager": "node --test tests/canvas_layer_manager_behavior.test.mjs",
    "test:node:political-raster-worker-packet": "node --test tests/political_raster_worker_packet_behavior.test.mjs",
    "test:node:perf-probe-snapshot-behavior": "node --test tests/perf_probe_snapshot_behavior.test.mjs",
    "test:node:scenario-chunk-contracts": "node --test tests/scenario_chunk_contracts.test.mjs",
    "test:node:scenario-chunk-contracts:quick": "node --test tests/scenario_chunk_contracts.quick.test.mjs",
    "test:node:scenario-chunk-contracts:heavy": "node --test tests/scenario_chunk_contracts.heavy.test.mjs",
    "test:node:scenario-chunk-contracts:split": "node --test tests/scenario_chunk_contracts.quick.test.mjs tests/scenario_chunk_contracts.heavy.test.mjs",
    "test:node:scenario-chunk-contracts:shadow": "node tools/verification/test_shadow_equivalence.mjs --shadow",
    "test:node:physical-layer-contracts": "node --test tests/physical_layer_contracts.test.mjs",
    "test:node:physical-layer-owner": "node --test tests/physical_layer_render_owner_behavior.test.mjs",
    "test:node:scenario-relief-overlay-owner": "node --test tests/scenario_relief_overlay_render_owner_behavior.test.mjs",
    "test:node:river-layer-contracts": "node --test tests/river_layer_contracts.test.mjs",
    "test:node:river-layer-owner": "node --test tests/river_layer_render_owner_behavior.test.mjs",
    "test:e2e:scenario-apply-concurrency": "node node_modules/@playwright/test/cli.js test tests/e2e/scenario_apply_concurrency.spec.js --workers=1 --retries=0",
    "test:e2e:startup-bundle-recovery-contract": "node node_modules/@playwright/test/cli.js test tests/e2e/startup_bundle_recovery_contract.spec.js --workers=1 --retries=0",
    "test:e2e:scenario-shell-overlay-contract": "node node_modules/@playwright/test/cli.js test tests/e2e/scenario_shell_overlay_contract.spec.js --workers=1 --retries=0",
    "test:e2e:physical-layer-regression": "node node_modules/@playwright/test/cli.js test tests/e2e/physical_layer_regression.spec.js --workers=1 --retries=0",
    "test:e2e:physical-layer-runtime-contract": "node node_modules/@playwright/test/cli.js test tests/e2e/physical_layer_runtime_contract.spec.js --workers=1 --retries=0",
    "test:e2e:dev:tno-ready-state": "node node_modules/@playwright/test/cli.js test tests/e2e/dev/tno_ready_state_contract.dev.spec.js --workers=1 --retries=0",
    "test:e2e:dev:scenario-chunk-runtime": "node node_modules/@playwright/test/cli.js test tests/e2e/dev/scenario_chunk_exact_after_settle_regression.dev.spec.js --workers=1 --retries=0",
    "test:e2e:dev:stage5-visual-acceptance": "node node_modules/@playwright/test/cli.js test tests/e2e/dev/full_visual_acceptance.dev.spec.js --workers=1 --retries=0",
    "test:e2e:dev:political-progressive-recovery": "node node_modules/@playwright/test/cli.js test tests/e2e/dev/scenario_chunk_exact_after_settle_regression.dev.spec.js --grep \"Great Lakes Congo political detail fill stable|post-edit keeps political detail fill|runtime color coverage\" --workers=1 --retries=0",
    "test:e2e:smoke": "node tools/e2e_layering.mjs run smoke",
    "test:e2e:strategic-overlay-smoke": "node node_modules/@playwright/test/cli.js test tests/e2e/strategic_overlay_smoke.spec.js --workers=1 --retries=0",
    "test:e2e:project-save-load": "node node_modules/@playwright/test/cli.js test tests/e2e/project_save_load_roundtrip.spec.js --workers=1",
    "test:e2e:interaction-funnel": "node node_modules/@playwright/test/cli.js test tests/e2e/interaction_funnel_contract.spec.js --workers=1 --retries=0",
    "test:e2e:scenario-resilience": "node tools/e2e_layering.mjs run-spec tests/e2e/scenario_apply_resilience.spec.js",
    "test:e2e:city-rendering": "node tools/e2e_layering.mjs run-spec tests/e2e/city_label_i18n_redraw.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/city_marker_visibility_regression.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/city_points_urban_runtime.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/city_reveal_plan_regression.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/city_urban_rendering_regression.spec.js",
    "test:e2e:water-rendering": "node tools/e2e_layering.mjs run-spec tests/e2e/river_layer_regression.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/tno_named_water_rendering.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/tno_open_ocean_rendering.spec.js && node tools/e2e_layering.mjs run-spec tests/e2e/water_cache_strategy_regression.spec.js",
    "test:e2e:tno-contracts": "node node_modules/@playwright/test/cli.js test tests/e2e/tno_startup_visible_context_layers_contract.spec.js tests/e2e/tno_1962_ui_smoke.spec.js --workers=1 --retries=0",
    "test:e2e:sample-guide": "node node_modules/@playwright/test/cli.js test tests/e2e/sample_guide_deeplink.spec.js --workers=1 --retries=0",
    "test:e2e:pages-public-release-gate": "node node_modules/@playwright/test/cli.js test tests/e2e/release/pages_public_release_gate.spec.js --workers=1 --retries=0",
    "test:e2e:pages-public-release-gate:deployed": "node node_modules/@playwright/test/cli.js test tests/e2e/release/pages_public_release_gate.spec.js --workers=1 --retries=0",
    "test:e2e:layer:smoke": "node tools/e2e_layering.mjs run smoke",
    "test:e2e:layer:contract": "node tools/e2e_layering.mjs run contract",
    "test:e2e:layer:regression": "node tools/e2e_layering.mjs run regression",
    "test:e2e:layer:feature": "node tools/e2e_layering.mjs run feature",
    "test:e2e:layer:all": "node tools/e2e_layering.mjs run all",
    "test:adaptive": "node tools/run_adaptive_tests.mjs",
    "test:adaptive:execute": "node tools/run_adaptive_tests.mjs --execute",
    "test:adaptive:execute:main-thread": "node tools/run_adaptive_tests.mjs --execute --include-main-thread",
    "verify:test:e2e-layers": "node tools/e2e_layering.mjs check",
    "verify:test-timeout-inventory": "node tools/test_timeout_inventory.mjs",
    "verify:test-import-graph": "node tools/check_test_import_graph.mjs",
    "verify:architecture-boundaries": "node tools/check_architecture_boundaries.mjs",
    "verify:supervisor-schemas": "node tools/ai_test_supervisor/check_supervisor_schemas.mjs",
    "test:node:supervisor-contracts": "node --test tests/supervisor_domain_registry_behavior.test.mjs tests/supervisor_schema_contracts.test.mjs",
    "test:node:supervisor-routing": "node --test tests/supervisor_adaptive_route_behavior.test.mjs",
    "test:node:supervisor-plan": "node --test tests/supervisor_change_dossier_behavior.test.mjs tests/supervisor_plan_behavior.test.mjs",
    "test:supervisor": "node tools/ai_test_supervisor/supervise_adaptive_verification.mjs",
    "test:supervisor:execute": "node tools/ai_test_supervisor/supervise_adaptive_verification.mjs --execute",
    "test:supervisor:execute:main-thread": "node tools/ai_test_supervisor/supervise_adaptive_verification.mjs --execute --include-main-thread",
    "verify:supervisor-plan": "npm run test:node:supervisor-plan && node tools/ai_test_supervisor/supervise_adaptive_verification.mjs --changed-file tools/ai_test_supervisor/supervise_adaptive_verification.mjs --changed-file tests/supervisor_plan_behavior.test.mjs",
    "verify:supervisor-contracts": "npm run verify:supervisor-schemas && npm run test:node:supervisor-contracts && npm run test:node:supervisor-routing",
    "test:node:verify-core-runner": "node --test tests/verify_core_runner_behavior.test.mjs tests/verify_commit_runner_behavior.test.mjs",
    "test:node:verification-profile": "node --test tests/verification_profile_behavior.test.mjs",
  "test:node:verification-metadata": "node --test tests/verification_metadata_behavior.test.mjs",
  "test:node:catalog-projection-history": "node --test tests/catalog_projection_shadow_behavior.test.mjs",
    "test:node:verification-script-portfolio": "node --test tests/verification_script_portfolio_behavior.test.mjs",
    "test:node:renderer-pass-family-inventory": "node --test tests/renderer_pass_family_inventory_behavior.test.mjs",
    "test:node:visual-effects-pass-owner": "node --test tests/visual_effects_pass_owner_behavior.test.mjs",
    "test:node:context-pass-orchestrator-owner": "node --test tests/context_pass_orchestrator_owner_behavior.test.mjs",
    "test:node:renderer-political-pass-orchestration-preflight": "node --test tests/renderer_political_pass_orchestration_preflight.test.mjs",
    "test:node:political-pass-orchestrator-owner": "node --test tests/political_pass_orchestrator_owner_behavior.test.mjs",
    "test:node:political-background-render-owner": "node --test tests/political_background_render_owner_behavior.test.mjs",
    "test:node:political-partial-repaint-owner": "node --test tests/political_partial_repaint_owner_behavior.test.mjs",
    "test:node:political-pass-orchestrator-owner-suite": "npm run test:node:political-pass-orchestrator-owner && npm run test:node:renderer-political-pass-orchestration-preflight && npm run test:python:map-renderer-political-pass-orchestrator-boundary",
    "test:python:map-renderer-political-pass-orchestrator-boundary": "npm run python -- -m unittest tests.test_map_renderer_political_pass_orchestrator_boundary_contract -q",
    "test:python:map-renderer-political-background-render-owner-boundary": "npm run python -- -m unittest tests.test_map_renderer_political_background_render_owner_boundary_contract -q",
    "test:python:map-renderer-political-partial-repaint-owner-boundary": "npm run python -- -m unittest tests.test_map_renderer_political_partial_repaint_owner_boundary_contract -q",
    "test:python:map-renderer-render-pipeline-passes-boundary": "npm run python -- -m unittest tests.test_map_renderer_render_pipeline_passes_boundary_contract tests.test_map_renderer_strategic_values_render_contract -q",
    "verify:core:list": "node tools/run_core_verification.mjs --list",
    "verify:core": "node tools/run_core_verification.mjs",
    "verify:core:main-thread": "node tools/run_core_verification.mjs --include-main-thread",
    "verify:script-portfolio": "node tools/verification/script_portfolio.mjs check",
    "verify:local-infra": "node --test tests/verification_script_portfolio_behavior.test.mjs tests/verification_metadata_behavior.test.mjs tests/verify_core_runner_behavior.test.mjs tests/verify_commit_runner_behavior.test.mjs tests/verification_profile_behavior.test.mjs && npm run python -- -m unittest tests.test_e2e_structural_tooling -q",
    "verify:commit": "node tools/run_commit_verification.mjs",
    "verify:edit": "npm run verify:script-portfolio && node tools/select_verification_targets.mjs --check && node tools/run_adaptive_tests.mjs --entrypoint edit --execute --defer-main-thread",
    "verify:impact": "node tools/run_adaptive_tests.mjs --entrypoint impact --execute --defer-main-thread",
    "verify:pr": "npm run verify:script-portfolio && npm run verify:test-import-graph && node tools/select_verification_targets.mjs --check && npm run verify:architecture-boundaries && npm run verify:test:e2e-layers && npm run verify:test-console-allowlist && npm run verify:test-timeout-guardrails && npm run python -- -m unittest tests.test_app_entry_resolver tests.test_main_deferred_detail_promotion_boundary_contract tests.test_scenario_chunk_refresh_contracts tests.test_scenario_renderer_bridge_boundary_contract tests.test_map_renderer_interaction_border_snapshot_orchestration_contract tests.test_perf_gate_contract tests.test_startup_shell tests.test_e2e_structural_tooling -q && npm run verify:scenario-contracts:strict && node tools/run_adaptive_tests.mjs --execute --defer-main-thread --history-base origin/main",
    "verify:demo": "node node_modules/@playwright/test/cli.js test tests/e2e/sample_guide_deeplink.spec.js --grep @golden-demo --workers=1 --retries=0",
    "verify:nightly": "npm run verify:core -- --include-reserved && npm run python -- -m unittest discover -s tests -p \"test_*.py\" && npm run test:e2e:sample-guide",
    "verify:release": "npm run verify:core:main-thread && npm run verify:demo && npm run test:e2e:pages-public-release-gate",
    "verify:test-console-allowlist": "node tools/check_console_allowlist_decay.mjs",
    "verify:test-timeout-guardrails": "node tools/check_test_timeout_guardrails.mjs",
    "verify:test-timing-summary": "node tools/test_timing_summary.mjs",
    "build:landing-showcase": "npm run python -- tools/build_landing_europe_1936_showcase.py",
    "build:landing-work-maps": "npm run python -- tools/build_landing_work_maps.py",
    "test:py:landing-map-asset-contracts": "npm run python -- -m unittest tests.test_landing_map_asset_contracts -q",
    "test:node:landing-showcase-view": "node --test tests/landing_showcase_view_behavior.test.mjs",
    "test:node:sample-project-contracts": "node --test tests/sample_project_contracts.test.mjs",
    "test:node:release-smoke-helper": "node --test tests/release_smoke_retry_behavior.node.test.mjs",
    "test:py:pages-dist-startup-shell-heavy": "npm run python -- -m unittest tests.test_pages_dist_startup_shell_heavy -q",
    "verify:pages-dist": "npm run python -- tools/build_pages_dist.py && npm run python -- -m unittest tests.test_pages_dist_startup_shell -q && npm run test:py:landing-map-asset-contracts && npm run test:node:landing-showcase-view",
    "verify:pages-dist-and-drift": "npm run python -- tools/build_pages_dist.py && npm run python -- -m unittest tests.test_pages_dist_startup_shell -q && npm run test:py:landing-map-asset-contracts && npm run test:node:landing-showcase-view && git diff --exit-code -- dist/.nojekyll dist/app.js dist/index.html dist/styles.css dist/assets dist/app/index.html dist/app/js dist/app/css dist/app/vendor dist/pages-dist-manifest.json",
    "verify:dist-drift": "npm run python -- tools/build_pages_dist.py && git diff --exit-code -- dist/.nojekyll dist/app.js dist/index.html dist/styles.css dist/assets dist/app/index.html dist/app/js dist/app/css dist/app/vendor dist/pages-dist-manifest.json",
    "build:global-transport-roads": "npm run python -- tools/build_global_transport_roads.py",
    "build:global-transport-rail": "npm run python -- tools/build_global_transport_rail.py",
    "build:global-transport-road-catalog": "npm run python -- tools/build_global_transport_catalogs.py --family road",
    "build:global-transport-airports": "npm run python -- tools/build_global_transport_points.py --family airport",
    "build:global-transport-ports": "npm run python -- tools/build_global_transport_points.py --family port",
    "verify:perf-gate-contract": "npm run python -- -m unittest tests.test_perf_gate_contract -q",
    "bench:editor-performance": "npm run python -- ops/browser-mcp/editor-performance-benchmark.py --out .runtime/output/perf/editor-performance-benchmark.json --screenshot-dir .runtime/browser/mcp-artifacts/perf",
    "bench:special-zones-members": "node tools/perf/special_zone_members_benchmark.mjs --members 240 --iterations 40 --out .runtime/output/perf/special-zone-members-benchmark.json",
    "bench:polyline-simplification": "node tools/perf/polyline_simplification_benchmark.mjs --iterations 40 --out .runtime/reports/generated/geometry-simplification-benchmark.json",
    "test:node:polyline-simplification-benchmark": "node --test tests/polyline_simplification_benchmark_contract.test.mjs"
  };
