#!/usr/bin/env python3
"""Build a lightweight modern city-lights asset from NASA Black Marble."""

from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:  # pragma: no cover - dependency guard
    raise SystemExit(
        "Pillow is required to build the city lights asset. "
        "Create a venv and install it with: python3 -m venv .venv && .venv/bin/pip install Pillow"
    ) from exc


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "js" / "core" / "city_lights_modern_asset.js"
DEFAULT_SOURCE_URL = (
    "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/"
    "144000/144897/BlackMarble_2016_01deg_gray.jpg"
)
DEFAULT_GRID_WIDTH = 360
DEFAULT_GRID_HEIGHT = 180
DEFAULT_BASE_THRESHOLD = 2
DEFAULT_CORRIDOR_THRESHOLD = 10


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a modern night-lights asset module from NASA Black Marble."
    )
    parser.add_argument(
        "--source-url",
        default=DEFAULT_SOURCE_URL,
        help="Remote grayscale equirectangular source image URL.",
    )
    parser.add_argument(
        "--source-file",
        default="",
        help="Optional local source image path. If provided, download is skipped.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Output JS module path.",
    )
    parser.add_argument(
        "--grid-width",
        type=int,
        default=DEFAULT_GRID_WIDTH,
        help="Output grid width in cells.",
    )
    parser.add_argument(
        "--grid-height",
        type=int,
        default=DEFAULT_GRID_HEIGHT,
        help="Output grid height in cells.",
    )
    parser.add_argument(
        "--base-threshold",
        type=int,
        default=DEFAULT_BASE_THRESHOLD,
        help="Recommended runtime base luminance threshold.",
    )
    parser.add_argument(
        "--corridor-threshold",
        type=int,
        default=DEFAULT_CORRIDOR_THRESHOLD,
        help="Recommended runtime corridor threshold.",
    )
    return parser.parse_args()


def fetch_source_image(source_url: str, source_file: str) -> tuple[Path, str]:
    if source_file:
        source_path = Path(source_file).expanduser().resolve()
        if not source_path.exists():
            raise SystemExit(f"Source file not found: {source_path}")
        return source_path, source_path.as_uri()

    build_cache_dir = PROJECT_ROOT / ".runtime" / "tmp" / "city_lights"
    build_cache_dir.mkdir(parents=True, exist_ok=True)
    target_path = build_cache_dir / Path(source_url).name
    if not target_path.exists():
        with urllib.request.urlopen(source_url, timeout=60) as response:
            target_path.write_bytes(response.read())
    return target_path, source_url


def load_grid_values(source_path: Path, width: int, height: int) -> list[int]:
    image = Image.open(source_path).convert("L")
    resized = image.resize((width, height), Image.Resampling.BOX)
    return list(resized.tobytes())


def format_uint8_array(values: list[int], indent: str = "  ", row_size: int = 32) -> str:
    rows = []
    for start in range(0, len(values), row_size):
        row = ", ".join(str(value) for value in values[start:start + row_size])
        rows.append(f"{indent}{row}")
    return ",\n".join(rows)


def write_module(
    output_path: Path,
    *,
    source_ref: str,
    width: int,
    height: int,
    base_threshold: int,
    corridor_threshold: int,
    values: list[int],
) -> None:
    step_lon = 360 / width
    step_lat = 180 / height
    module_text = f"""// Generated by tools/build_city_lights_modern_asset.py
// Source: {source_ref}
// NASA Black Marble 2016 grayscale, resampled into a lightweight 1-layer luminance grid.

export const MODERN_CITY_LIGHTS_SOURCE = Object.freeze({{
  name: "NASA Black Marble 2016 (grayscale)",
  url: {source_ref!r},
}});

export const MODERN_CITY_LIGHTS_GRID_WIDTH = {width};
export const MODERN_CITY_LIGHTS_GRID_HEIGHT = {height};
export const MODERN_CITY_LIGHTS_STEP_LON_DEG = {step_lon:.12g};
export const MODERN_CITY_LIGHTS_STEP_LAT_DEG = {step_lat:.12g};
export const MODERN_CITY_LIGHTS_BASE_THRESHOLD = {base_threshold};
export const MODERN_CITY_LIGHTS_CORRIDOR_THRESHOLD = {corridor_threshold};
export const MODERN_CITY_LIGHTS_GRID = new Uint8Array([
{format_uint8_array(values)}
]);
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(module_text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    output_path = Path(args.output).expanduser().resolve()
    source_path, source_ref = fetch_source_image(args.source_url, args.source_file)
    values = load_grid_values(source_path, args.grid_width, args.grid_height)
    write_module(
        output_path,
        source_ref=source_ref,
        width=args.grid_width,
        height=args.grid_height,
        base_threshold=args.base_threshold,
        corridor_threshold=args.corridor_threshold,
        values=values,
    )
    print(
        f"Built modern city lights asset: {output_path} "
        f"(cells={args.grid_width}x{args.grid_height}, source={source_ref})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
