"""Shared upstream source catalog for smoke checks and source-freeze audits."""
from __future__ import annotations

from map_builder import config as cfg


SOURCE_SPECS = {
    "fr_arr": {
        "label": "France arrondissements",
        "url": cfg.FR_ARR_URL,
        "filename": cfg.FR_ARR_FILENAME,
        "fallback_urls": cfg.FR_ARR_FALLBACK_URLS,
        "kind": "community_geojson",
    },
    "pl_powiaty": {
        "label": "Poland powiaty",
        "url": cfg.PL_POWIATY_URL,
        "filename": cfg.PL_POWIATY_FILENAME,
        "fallback_urls": cfg.PL_POWIATY_FALLBACK_URLS,
        "kind": "community_geojson",
    },
    "gb_chn_adm2": {
        "label": "geoBoundaries China ADM2",
        "url": cfg.CHINA_CITY_URL,
        "filename": cfg.CHINA_ADM2_FILENAME,
        "fallback_urls": cfg.CHINA_CITY_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "CHN",
        "adm": "ADM2",
    },
    "gb_cze_adm2": {
        "label": "geoBoundaries Czechia ADM2",
        "url": cfg.CZE_ADM2_URL,
        "filename": cfg.CZE_ADM2_FILENAME,
        "fallback_urls": cfg.CZE_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "CZE",
        "adm": "ADM2",
    },
    "gb_dnk_adm2": {
        "label": "geoBoundaries Denmark ADM2",
        "url": cfg.DNK_ADM2_URL,
        "filename": cfg.DNK_ADM2_FILENAME,
        "fallback_urls": cfg.DNK_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "DNK",
        "adm": "ADM2",
    },
    "gb_svk_adm2": {
        "label": "geoBoundaries Slovakia ADM2",
        "url": cfg.SVK_ADM2_URL,
        "filename": cfg.SVK_ADM2_FILENAME,
        "fallback_urls": cfg.SVK_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "SVK",
        "adm": "ADM2",
    },
    "gb_rus_adm2": {
        "label": "geoBoundaries Russia ADM2",
        "url": cfg.RUS_ADM2_URL,
        "filename": cfg.RUS_ADM2_FILENAME,
        "fallback_urls": cfg.RUS_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "RUS",
        "adm": "ADM2",
    },
    "gb_ukr_adm2": {
        "label": "geoBoundaries Ukraine ADM2",
        "url": cfg.UKR_ADM2_URL,
        "filename": cfg.UKR_ADM2_FILENAME,
        "fallback_urls": cfg.UKR_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "UKR",
        "adm": "ADM2",
    },
    "gb_blr_adm2": {
        "label": "geoBoundaries Belarus ADM2",
        "url": cfg.BLR_ADM2_URL,
        "filename": cfg.BLR_ADM2_FILENAME,
        "fallback_urls": cfg.BLR_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "BLR",
        "adm": "ADM2",
    },
    "gb_ind_adm2": {
        "label": "geoBoundaries India ADM2",
        "url": cfg.IND_ADM2_URL,
        "filename": cfg.IND_ADM2_FILENAME,
        "fallback_urls": cfg.IND_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "IND",
        "adm": "ADM2",
    },
    "gb_mex_adm2": {
        "label": "geoBoundaries Mexico ADM2",
        "url": cfg.MEX_ADM2_URL,
        "filename": cfg.MEX_ADM2_FILENAME,
        "fallback_urls": cfg.MEX_ADM2_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "MEX",
        "adm": "ADM2",
    },
    "gb_bih_adm1": {
        "label": "geoBoundaries Bosnia and Herzegovina ADM1",
        "url": cfg.BIH_ADM1_URL,
        "filename": cfg.BIH_ADM1_FILENAME,
        "fallback_urls": cfg.BIH_ADM1_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "BIH",
        "adm": "ADM1",
    },
    "gb_idn_adm1": {
        "label": "geoBoundaries Indonesia ADM1",
        "url": cfg.IDN_ADM1_URL,
        "filename": cfg.IDN_ADM1_FILENAME,
        "fallback_urls": cfg.IDN_ADM1_FALLBACK_URLS,
        "kind": "geoboundaries",
        "iso": "IDN",
        "adm": "ADM1",
    },
    "gb_bfa_adm1": {
        "label": "geoBoundaries Burkina Faso ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["BF"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["BF"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["BF"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "BFA",
        "adm": "ADM1",
    },
    "gb_gin_adm1": {
        "label": "geoBoundaries Guinea ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["GN"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["GN"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["GN"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "GIN",
        "adm": "ADM1",
    },
    "gb_civ_adm1": {
        "label": "geoBoundaries Cote d'Ivoire ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["CI"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["CI"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["CI"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "CIV",
        "adm": "ADM1",
    },
    "gb_mwi_adm1": {
        "label": "geoBoundaries Malawi ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["MW"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["MW"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["MW"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "MWI",
        "adm": "ADM1",
    },
    "gb_uga_adm1": {
        "label": "geoBoundaries Uganda ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["UG"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["UG"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["UG"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "UGA",
        "adm": "ADM1",
    },
    "gb_som_adm1": {
        "label": "geoBoundaries Somalia ADM1",
        "url": cfg.AFRICA_BASIC_GB_OVERRIDES["SO"]["url"],
        "filename": cfg.AFRICA_BASIC_GB_OVERRIDES["SO"]["filename"],
        "fallback_urls": cfg.AFRICA_BASIC_GB_OVERRIDES["SO"]["fallback_urls"],
        "kind": "geoboundaries",
        "iso": "SOM",
        "adm": "ADM1",
    },
}

SOURCE_GROUPS = {
    "phase1_foundation": ["fr_arr", "pl_powiaty"],
    "geoboundaries_phase2": [
        "gb_chn_adm2",
        "gb_cze_adm2",
        "gb_dnk_adm2",
        "gb_svk_adm2",
        "gb_rus_adm2",
        "gb_ukr_adm2",
        "gb_blr_adm2",
        "gb_ind_adm2",
        "gb_mex_adm2",
        "gb_bih_adm1",
        "gb_idn_adm1",
        "gb_bfa_adm1",
        "gb_gin_adm1",
        "gb_civ_adm1",
        "gb_mwi_adm1",
        "gb_uga_adm1",
        "gb_som_adm1",
    ],
}

