// Canonical runtime hook names and bus event names.
// bus.js 只关心通用事件能力，这里负责项目内的名字真源。

const STATE_BUS_EVENT_BY_HOOK_NAME = Object.freeze({
  updateRecentUI: "ui:update-recent",
  updateHistoryUIFn: "history:update-ui",
  updateLegendUI: "sidebar:update-legend",
  updateSwatchUIFn: "toolbar:update-swatch",
  updatePaletteSourceUIFn: "palette:update-source-ui",
  updatePaletteLibraryUIFn: "palette:update-library-ui",
  updateScenarioUIFn: "scenario:update-ui",
  renderPaletteFn: "palette:render",
  updateToolUIFn: "toolbar:update-tool-ui",
  updateToolbarInputsFn: "toolbar:update-inputs",
  updatePaintModeUIFn: "toolbar:update-paint-mode",
  updateActiveSovereignUIFn: "toolbar:update-active-sovereign",
  updateDynamicBorderStatusUIFn: "toolbar:update-dynamic-border-status",
  updateZoomUIFn: "toolbar:update-zoom",
  updateTextureUIFn: "toolbar:update-texture",
  updateWaterInteractionUIFn: "sidebar:update-water-interaction",
  updateTransportAppearanceUIFn: "toolbar:update-transport-appearance",
  updateFacilityInfoCardUiFn: "transport:update-facility-card-ui",
  syncFacilityInfoCardVisibilityFn: "transport:sync-facility-card-visibility",
  updateScenarioSpecialRegionUIFn: "sidebar:update-scenario-special-region",
  updateScenarioReliefOverlayUIFn: "sidebar:update-scenario-relief-overlay",
  updateParentBorderCountryListFn: "sidebar:update-parent-border-country-list",
  updateSpecialZoneEditorUIFn: "toolbar:update-special-zone-editor",
  updateStrategicOverlayUIFn: "strategic-overlay:update-ui",
  updateScenarioContextBarFn: "scenario:update-context-bar",
  updateWorkspaceStatusFn: "workspace:update-status",
  updateDockCollapsedUiFn: "workspace:update-dock-collapsed-ui",
  triggerScenarioGuideFn: "scenario:trigger-guide",
  syncDeveloperModeUiFn: "workspace:sync-developer-mode-ui",
  renderCountryListFn: "sidebar:render-country-list",
  refreshCountryListRowsFn: "sidebar:refresh-country-list-rows",
  refreshCountryInspectorDetailFn: "sidebar:refresh-country-inspector-detail",
  renderWaterRegionListFn: "sidebar:render-water-region-list",
  refreshWaterRegionListRowsFn: "sidebar:refresh-water-region-list-rows",
  renderSpecialRegionListFn: "sidebar:render-special-region-list",
  refreshSpecialRegionListRowsFn: "sidebar:refresh-special-region-list-rows",
  renderPresetTreeFn: "sidebar:render-preset-tree",
  renderScenarioAuditPanelFn: "scenario:render-audit-panel",
  updateDevWorkspaceUIFn: "workspace:update-dev-workspace-ui",
  refreshTransportWorkbenchUiFn: "transport:refresh-workbench-ui",
  refreshColorStateFn: "render:refresh-color-state",
  recomputeDynamicBordersNowFn: "render:recompute-dynamic-borders",
  renderNowFn: "render:flush-now",
  showToastFn: "app:show-toast",
});

const STATE_BUS_EVENT_ALIASES = Object.freeze({
  UPDATE_RECENT_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateRecentUI,
  UPDATE_HISTORY_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateHistoryUIFn,
  UPDATE_LEGEND_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateLegendUI,
  UPDATE_SWATCH_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateSwatchUIFn,
  UPDATE_PALETTE_SOURCE: STATE_BUS_EVENT_BY_HOOK_NAME.updatePaletteSourceUIFn,
  UPDATE_PALETTE_LIBRARY: STATE_BUS_EVENT_BY_HOOK_NAME.updatePaletteLibraryUIFn,
  UPDATE_SCENARIO_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateScenarioUIFn,
  RENDER_PALETTE: STATE_BUS_EVENT_BY_HOOK_NAME.renderPaletteFn,
  UPDATE_TOOL_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateToolUIFn,
  UPDATE_TOOLBAR_INPUTS: STATE_BUS_EVENT_BY_HOOK_NAME.updateToolbarInputsFn,
  UPDATE_PAINT_MODE: STATE_BUS_EVENT_BY_HOOK_NAME.updatePaintModeUIFn,
  UPDATE_ACTIVE_SOVEREIGN_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateActiveSovereignUIFn,
  UPDATE_DYNAMIC_BORDER_STATUS: STATE_BUS_EVENT_BY_HOOK_NAME.updateDynamicBorderStatusUIFn,
  UPDATE_ZOOM_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateZoomUIFn,
  UPDATE_TEXTURE_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateTextureUIFn,
  UPDATE_WATER_INTERACTION: STATE_BUS_EVENT_BY_HOOK_NAME.updateWaterInteractionUIFn,
  UPDATE_TRANSPORT_APPEARANCE_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateTransportAppearanceUIFn,
  UPDATE_FACILITY_INFO_CARD_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateFacilityInfoCardUiFn,
  SYNC_FACILITY_INFO_CARD_VISIBILITY: STATE_BUS_EVENT_BY_HOOK_NAME.syncFacilityInfoCardVisibilityFn,
  UPDATE_SCENARIO_SPECIAL_REGION: STATE_BUS_EVENT_BY_HOOK_NAME.updateScenarioSpecialRegionUIFn,
  UPDATE_SCENARIO_RELIEF_OVERLAY: STATE_BUS_EVENT_BY_HOOK_NAME.updateScenarioReliefOverlayUIFn,
  UPDATE_PARENT_BORDER_COUNTRY_LIST: STATE_BUS_EVENT_BY_HOOK_NAME.updateParentBorderCountryListFn,
  UPDATE_SPECIAL_ZONE_EDITOR_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateSpecialZoneEditorUIFn,
  UPDATE_STRATEGIC_OVERLAY_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateStrategicOverlayUIFn,
  UPDATE_SCENARIO_CONTEXT_BAR: STATE_BUS_EVENT_BY_HOOK_NAME.updateScenarioContextBarFn,
  UPDATE_WORKSPACE_STATUS: STATE_BUS_EVENT_BY_HOOK_NAME.updateWorkspaceStatusFn,
  UPDATE_DOCK_COLLAPSED_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateDockCollapsedUiFn,
  TRIGGER_SCENARIO_GUIDE: STATE_BUS_EVENT_BY_HOOK_NAME.triggerScenarioGuideFn,
  SYNC_DEVELOPER_MODE_UI: STATE_BUS_EVENT_BY_HOOK_NAME.syncDeveloperModeUiFn,
  RENDER_COUNTRY_LIST: STATE_BUS_EVENT_BY_HOOK_NAME.renderCountryListFn,
  REFRESH_COUNTRY_LIST_ROWS: STATE_BUS_EVENT_BY_HOOK_NAME.refreshCountryListRowsFn,
  REFRESH_COUNTRY_INSPECTOR_DETAIL: STATE_BUS_EVENT_BY_HOOK_NAME.refreshCountryInspectorDetailFn,
  RENDER_WATER_REGION_LIST: STATE_BUS_EVENT_BY_HOOK_NAME.renderWaterRegionListFn,
  REFRESH_WATER_REGION_LIST_ROWS: STATE_BUS_EVENT_BY_HOOK_NAME.refreshWaterRegionListRowsFn,
  RENDER_SPECIAL_REGION_LIST: STATE_BUS_EVENT_BY_HOOK_NAME.renderSpecialRegionListFn,
  REFRESH_SPECIAL_REGION_LIST_ROWS: STATE_BUS_EVENT_BY_HOOK_NAME.refreshSpecialRegionListRowsFn,
  RENDER_PRESET_TREE: STATE_BUS_EVENT_BY_HOOK_NAME.renderPresetTreeFn,
  RENDER_SCENARIO_AUDIT_PANEL: STATE_BUS_EVENT_BY_HOOK_NAME.renderScenarioAuditPanelFn,
  UPDATE_DEV_WORKSPACE_UI: STATE_BUS_EVENT_BY_HOOK_NAME.updateDevWorkspaceUIFn,
  REFRESH_TRANSPORT_WORKBENCH_UI: STATE_BUS_EVENT_BY_HOOK_NAME.refreshTransportWorkbenchUiFn,
  REFRESH_COLOR_STATE: STATE_BUS_EVENT_BY_HOOK_NAME.refreshColorStateFn,
  RECOMPUTE_DYNAMIC_BORDERS_NOW: STATE_BUS_EVENT_BY_HOOK_NAME.recomputeDynamicBordersNowFn,
  RENDER_NOW: STATE_BUS_EVENT_BY_HOOK_NAME.renderNowFn,
  SHOW_TOAST: STATE_BUS_EVENT_BY_HOOK_NAME.showToastFn,
});

export const STATE_BUS_EVENTS = Object.freeze({
  ...STATE_BUS_EVENT_BY_HOOK_NAME,
  ...STATE_BUS_EVENT_ALIASES,
});

export const STATE_NOTIFICATION_HOOK_NAMES = Object.freeze(Object.keys(STATE_BUS_EVENT_BY_HOOK_NAME));

export const STATE_HANDLER_HOOK_NAMES = Object.freeze([
  "toggleLeftPanelFn",
  "toggleRightPanelFn",
  "toggleDockFn",
  "toggleDeveloperModeFn",
  "setDevWorkspaceExpandedFn",
  "openTransportWorkbenchFn",
  "closeTransportWorkbenchFn",
  "openExportWorkbenchFn",
  "closeExportWorkbenchFn",
  "openScenarioVisualAdjustmentsFn",
  "closeDockPopoverFn",
  "restoreSupportSurfaceFromUrlFn",
  "showOnboardingHintFn",
  "dismissOnboardingHintFn",
  "commitZoomInputValueFn",
  "runZoomStepFn",
  "runZoomResetFn",
  "runToolSelectionFn",
  "runBrushModeToggleFn",
  "runHistoryActionFn",
  "persistViewSettingsFn",
  "setStartupReadonlyStateFn",
  "ensureFullLocalizationDataReadyFn",
  "getViewportGeoBoundsFn",
  "scheduleScenarioChunkRefreshFn",
  "cancelScenarioChunkPromotionCommitFn",
  "ensureBaseCityDataFn",
  "ensureContextLayerDataFn",
  "releaseDeferredContextBasePassFn",
  "ensureDetailTopologyFn",
  "getStrategicOverlayPerfCountersFn",
]);
