// Content/data state defaults.
// 这里收口 localization、topology、context layer 和底图数据默认 shape，
// 避免 state.js 与 consumer reset/fallback 再次各写一份。

export function createDefaultLocalesState() {
  return {
    ui: {},
    geo: {},
  };
}

export function createDefaultContextLayerLoadStateByName() {
  return {
    rivers: "idle",
    urban: "idle",
    airports: "idle",
    ports: "idle",
    roads: "idle",
    road_labels: "idle",
    railways: "idle",
    rail_stations_major: "idle",
    physical: "idle",
    physical_semantics: "idle",
    physical_contours_major: "idle",
    physical_contours_minor: "idle",
  };
}

export function createDefaultContentState() {
  return {
    locales: createDefaultLocalesState(),
    baseLocalizationLevel: "full",
    baseLocalizationDataState: "idle",
    baseLocalizationDataError: "",
    baseLocalizationDataPromise: null,
    baseGeoLocales: {},
    geoAliasToStableKey: {},
    baseGeoAliasToStableKey: {},
    currentLanguage: globalThis.currentLanguage || "en",
    topology: null,
    topologyPrimary: null,
    topologyDetail: null,
    runtimePoliticalTopology: null,
    defaultRuntimePoliticalTopology: null,
    ruCityOverrides: null,
    topologyBundleMode: "single",
    renderProfile: "auto",
    detailDeferred: false,
    detailSourceRequested: "na_v2",
    detailPromotionInFlight: false,
    detailPromotionCompleted: false,
    scenarioApplyInFlight: false,
    parentBordersVisible: true,
    landData: null,
    landDataFull: null,
    specialZonesData: null,
    specialZonesExternalData: null,
    contextLayerExternalDataByName: {},
    contextLayerRevision: 0,
    contextLayerLoadStateByName: createDefaultContextLayerLoadStateByName(),
    contextLayerLoadErrorByName: {},
    contextLayerLoadPromiseByName: {},
    specialZones: {},
    waterRegionsData: null,
    riversData: null,
    airportsData: null,
    portsData: null,
    roadsData: null,
    roadLabelsData: null,
    railwaysData: null,
    railStationsMajorData: null,
    oceanData: null,
    globalBathymetryTopologyData: null,
    globalBathymetryBandsData: null,
    globalBathymetryContoursData: null,
    globalBathymetryTopologyUrl: "",
    activeBathymetryBandsData: null,
    activeBathymetryContoursData: null,
    activeBathymetrySource: "none",
    activeBathymetryTopologyUrl: "",
    oceanMaskMode: "topology_ocean",
    oceanMaskQuality: 1,
    landBgData: null,
    urbanData: null,
    urbanLayerCapability: null,
    worldCitiesData: null,
    baseCityAliasesData: null,
    baseCityDataState: "idle",
    baseCityDataError: "",
    baseCityDataPromise: null,
    physicalData: null,
    physicalSemanticsData: null,
    physicalContourMajorData: null,
    physicalContourMinorData: null,
    hierarchyData: null,
    hierarchyGroupsByCode: new Map(),
    countryGroupsData: null,
    countryGroupMetaByCode: new Map(),
    countryInteractionPoliciesByCode: new Map(),
    layerDataDiagnostics: {},
    contextLayerSourceByName: {},
    width: 0,
    height: 0,
    dpr: globalThis.devicePixelRatio || 1,
  };
}
