name: pr-verify

on:
  pull_request:

jobs:
  pr-verify-fast:
    uses: ./.github/workflows/verify-shared.yml
    with:
      profile: pr-fast
      run-e2e-smoke: false

  pr-verify-smoke:
    needs: pr-verify-fast
    uses: ./.github/workflows/verify-shared.yml
    with:
      profile: pr-smoke
      run-e2e-smoke: true
